name: cartly
description: "Cartly shopping assistant."

publish_to: 'none'

version: 1.0.3+81

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  camera: ^0.11.3
  image_picker: ^1.1.2
  file_selector: ^1.1.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  google_mobile_ads: ^5.1.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_slidable: ^3.1.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/


  fonts:
    # =========================
    # Pretendard (본문용)
    # =========================
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800

    # =========================
    # Space Grotesk (타이틀용)
    # =========================
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
