export const ADMIN_COPY_DEFAULTS: Record<string, string> = {
  'admin.nav.brand': 'Cartly Admin',
  'admin.nav.overview': 'Overview',
  'admin.nav.users': 'Users',
  'admin.nav.scanOps': 'Scan Ops',
  'admin.nav.carts': 'Carts',
  'admin.nav.ads': 'Ads',
  'admin.nav.content': 'Content',
  'admin.nav.config': 'Config',
  'admin.nav.logout': '로그아웃',
  'admin.nav.loggingOut': '정리 중...',
  'admin.common.refresh': '데이터 불러오기',
  'admin.common.refreshing': '불러오는 중...',
  'admin.copy.toggle': '수정 모드',
  'admin.copy.panelTitle': '현재 페이지 문구 수정',
  'admin.copy.panelDesc': 'Config 페이지는 제외하고, 현재 화면에 보이는 고정 문구를 바로 수정한다.',
  'admin.copy.save': '문구 저장',
  'admin.copy.saving': '저장 중...',
  'admin.copy.cancel': '취소',
  'admin.copy.saved': '문구 저장 완료',
  'admin.copy.saveFailed': '문구 저장 실패',
  'admin.copy.empty': '이 페이지에 등록된 문구가 아직 없어',
  'admin.copy.field.common': '공통',
  'admin.copy.field.page': '페이지',
  'admin.login.eyebrow': 'Protected admin',
  'admin.login.title': 'Cartly Admin 로그인',
  'admin.login.desc': '외부 접속용 운영 보드야. 관리자 비밀번호로만 들어오게 막아뒀어.',
  'admin.login.passwordLabel': '관리자 비밀번호',
  'admin.login.passwordPlaceholder': '비밀번호 입력',
  'admin.login.submit': '들어가기',
  'admin.login.submitting': '확인 중...',
  'admin.login.error.expired': '세션이 만료됐거나 비밀번호가 바뀌었어. 다시 로그인해.',
  'admin.login.error.invalid': '비밀번호가 맞지 않아. 다시 확인해.',
  'admin.login.error.failed': '로그인에 실패했어',
  'admin.overview.title': 'Overview',
  'admin.overview.desc': '핵심 지표 요약',
  'admin.overview.snapshot.data': 'Data',
  'admin.overview.snapshot.scan': 'Scan',
  'admin.overview.snapshot.members': 'Members',
  'admin.overview.snapshot.ad': 'Ad',
  'admin.overview.cumulative.users': 'Users',
  'admin.overview.cumulative.scan': 'Scan',
  'admin.overview.cumulative.ad': 'Ad',
  'admin.overview.period.title': '누적 보기',
  'admin.overview.period.desc': '선택한 기간 안에서 집계된 누적 값',
  'admin.users.title': 'Users',
  'admin.users.desc': '사용자 목록',
  'admin.users.legacy.title': 'Legacy guest cleanup queue',
  'admin.users.legacy.desc': '자동 병합은 하지 않고, 운영자가 archive/merge 판단할 대상을 모아둔 목록',
  'admin.users.legacy.empty': '정리할 legacy guest가 없어',
  'admin.users.legacy.archive': 'Archive',
  'admin.users.legacy.archiving': '처리 중...',
  'admin.users.legacy.merge': 'Merge 판단',
  'admin.scanops.title': 'Scan Ops',
  'admin.scanops.desc': '작업 상태 + feedback/failure 루프',
  'admin.scanops.feedback.title': 'Recent feedback',
  'admin.scanops.feedback.desc': '사용자가 그대로 수락했는지, 수정 후 담았는지',
  'admin.scanops.feedback.empty': '아직 feedback 로그가 없어',
  'admin.scanops.failures.title': 'Recent failures',
  'admin.scanops.failures.desc': 'submit / processing / polling / result 단계 실패를 본다',
  'admin.scanops.failures.empty': '아직 failure 로그가 없어',
  'admin.carts.title': 'Carts',
  'admin.carts.desc': '고객별 저장 카트 히스토리',
  'admin.carts.filters.title': '필터',
  'admin.carts.filters.desc': '고객/날짜 기준으로 조회하고 같은 조건으로 다운로드',
  'admin.carts.filters.downloadXlsx': 'Excel(.xlsx) 다운로드',
  'admin.carts.filters.downloadCsv': 'CSV 다운로드',
  'admin.carts.filters.reset': '초기화',
  'admin.carts.filters.apply': '필터 적용',
  'admin.carts.history.title': '저장 카트 히스토리',
  'admin.carts.history.desc': 'snapshot lineage와 저장 시점별 상품 구성을 함께 본다',
  'admin.carts.history.empty': '조건에 맞는 저장 카트가 없어',
  'admin.ads.title': 'Ads',
  'admin.ads.desc': '광고 슬롯과 배너 자산 관리',
  'admin.ads.filters.title': '지난 광고 필터',
  'admin.ads.filters.desc': '유형/상태/검색어와 기간으로 지난 광고를 좁혀보고, 같은 조건으로 일괄 다운로드',
  'admin.ads.filters.search': '검색',
  'admin.ads.filters.variant': '유형',
  'admin.ads.filters.status': '상태',
  'admin.ads.filters.periodFrom': '시작일',
  'admin.ads.filters.periodTo': '종료일',
  'admin.ads.filters.bulkExport': '기간내 지난광고 Excel 일괄 다운로드',
  'admin.ads.history.title': '지난 광고 데이터',
  'admin.ads.history.desc': '이 슬롯에 연결되었던 지난 광고 성과 기록',
  'admin.ads.history.empty': '조건에 맞는 지난 광고가 없어',
  'admin.ads.livePanel.title': '현재 노출 광고',
  'admin.ads.livePanel.desc': '현재 앱에 노출 중인 광고 설정',
  'admin.ads.livePanel.save': '현재 광고 저장',
  'admin.ads.reservedPanel.title': '예약 광고 세팅',
  'admin.ads.reservedPanel.desc': '다음 노출 순서를 미리 준비하는 예약 광고 설정',
  'admin.ads.reservedPanel.save': '예약 광고 저장',
  'admin.ads.preview.title': '노출 위치 미리보기',
  'admin.ads.preview.empty': '이 슬롯용 미리보기가 아직 준비되지 않았어',
  'admin.ads.saving': '저장 중...',
  'admin.ads.uploading': '업로드 중...',
  'admin.ads.upload.liveDone': '현재',
  'admin.ads.upload.reservedDone': '예약',
  'admin.ads.upload.doneSuffix': '배너 업로드 완료',
  'admin.ads.fields.status': '상태',
  'admin.ads.fields.slotLabel': '슬롯 이름',
  'admin.ads.fields.slotDescription': '슬롯 설명',
  'admin.ads.fields.placementNote': '노출 위치 설명',
  'admin.ads.fields.title': '제목',
  'admin.ads.fields.message': '문구',
  'admin.ads.fields.cta': 'CTA',
  'admin.ads.fields.link': '링크',
  'admin.ads.fields.exposureWindow': '노출 기간',
  'admin.ads.fields.reservationWindow': '예약 기간',
  'admin.ads.fields.exposureStart': '노출 시작',
  'admin.ads.fields.exposureEnd': '노출 종료',
  'admin.ads.fields.reservationStart': '예약 시작',
  'admin.ads.fields.reservationEnd': '예약 종료',
  'admin.ads.fields.assetUpload': '배너 업로드',
  'admin.ads.fields.assetSelect': '배너 파일 선택',
  'admin.ads.fields.liveAssetDesc': '현재 노출 배너 자산',
  'admin.ads.fields.reservedAssetDesc': '예약용 배너 자산',
  'admin.ads.fields.connected': '연결됨:',
  'admin.ads.history.table.title': '광고명',
  'admin.ads.history.table.variant': '유형',
  'admin.ads.history.table.status': '상태',
  'admin.ads.history.table.period': '기간',
  'admin.ads.history.table.impressions': 'Impressions',
  'admin.ads.history.table.clicks': 'Clicks',
  'admin.ads.history.table.ctr': 'CTR',
  'admin.ads.history.table.image': '이미지',
  'admin.ads.history.table.download': '다운로드',
  'admin.ads.history.variant.live': '현재 광고 이력',
  'admin.ads.history.variant.reserved': '예약 광고 이력',
  'admin.ads.history.noMessage': '메시지 없음',
  'admin.ads.history.downloadSingle': 'Excel 다운로드',
  'admin.content.title': 'Content',
  'admin.content.desc': '앱 문구와 로고 관리',
  'admin.content.assets.title': '브랜드 자산',
  'admin.content.preview.title': '프리뷰',
  'admin.content.preview.splash': 'Splash',
  'admin.content.preview.noSplash': '등록된 스플래시 이미지 없음',
  'admin.content.preview.login': '로그인 화면',
  'admin.content.guide.title': '업로드 가이드',
  'admin.content.guide.logo': '로고: PNG, JPG, WEBP, SVG',
  'admin.content.guide.splash': '스플래시: PNG, JPG, WEBP',
  'admin.content.guide.size': '최대 용량: 8MB 이하',
  'admin.content.guide.save': '저장해야 앱 설정에 반영돼',
  'admin.content.loadFailed': '브랜딩 데이터를 불러오지 못했어',
  'admin.content.saveDone': '브랜딩 설정 저장 완료',
  'admin.content.saveFailed': '브랜딩 저장 실패',
  'admin.content.uploadFailed': '이미지 업로드 실패',
  'admin.content.upload.logoDone': '로고 업로드 완료',
  'admin.content.upload.splashDone': '스플래시 이미지 업로드 완료',
  'admin.content.uploading': '업로드 중...',
  'admin.content.fields.logoType': '로고 타입',
  'admin.content.fields.logoUpload': '로고 업로드',
  'admin.content.fields.logoUploadSelect': '로고 파일 선택',
  'admin.content.fields.logoUploadDesc': '직접 업로드해서 바로 연결',
  'admin.content.fields.splashUpload': '스플래시 이미지 업로드',
  'admin.content.fields.splashUploadSelect': '스플래시 파일 선택',
  'admin.content.fields.splashUploadDesc': '앱 시작 화면용 이미지 등록',
  'admin.content.fields.connected': '연결됨:',
  'admin.content.groups.branding.title': '기본 브랜딩',
  'admin.content.groups.branding.desc': '로고 모드와 탭 라벨',
  'admin.content.groups.savedHome.title': '지난 카트 / Home 카피',
  'admin.content.groups.savedHome.desc': '홈과 My 내부 지난 카트 문구',
  'admin.content.groups.help.title': '도움 탭 카피',
  'admin.content.groups.help.desc': '중간 도움 탭 문구',
  'admin.content.groups.myLogin.title': 'My / 로그인 카피',
  'admin.content.groups.myLogin.desc': '로그인과 My 화면 문구',
  'admin.content.groups.saveComplete.title': '저장 완료 카피',
  'admin.content.groups.saveComplete.desc': '저장 완료 문구',
  'admin.content.fields.logoText': '로고 텍스트',
  'admin.content.fields.homeTabLabel': 'Home 탭 라벨',
  'admin.content.fields.helpTabLabel': '도움 탭 라벨',
  'admin.content.fields.myTabLabel': 'My 탭 라벨',
  'admin.content.fields.helpPageTitle': '도움 페이지 제목',
  'admin.content.fields.helpSubtitle': '도움 subtitle',
  'admin.content.fields.homeRecentSavedAction': '지난 카트 보기 버튼',
  'admin.content.fields.savedPageTitle': '지난 카트 섹션 제목',
  'admin.content.fields.homeSubtitle': 'Home subtitle',
  'admin.content.fields.savedSubtitle': '지난 카트 설명',
  'admin.content.fields.savedEmptyTitle': '지난 카트 empty 제목',
  'admin.content.fields.savedEmptyBody': '지난 카트 empty 설명',
  'admin.content.fields.recentSavedTitle': '최근 저장 카트 제목',
  'admin.content.fields.recentSavedEmptyBody': '최근 저장 카트 empty 설명',
  'admin.content.fields.myPageTitle': 'My 페이지 제목',
  'admin.content.fields.mySubtitle': 'My subtitle',
  'admin.content.fields.myBenefitsTitle': 'My benefits 제목',
  'admin.content.fields.myBenefitsBody': 'My benefits 설명',
  'admin.content.fields.loginPageTitle': '로그인 페이지 제목',
  'admin.content.fields.loginSubtitle': 'Login subtitle',
  'admin.content.fields.loginBenefitsTitle': '로그인 benefits 제목',
  'admin.content.fields.loginBenefitsBody': '로그인 benefits 설명',
  'admin.content.fields.drawerGuestTitle': 'Drawer guest 제목',
  'admin.content.fields.drawerGuestBody': 'Drawer guest 설명',
  'admin.content.fields.saveCompleteTitle': '저장 완료 제목',
  'admin.content.fields.saveCompleteSubtitle': '저장 완료 부제',
  'admin.content.fields.saveCompleteViewSavedAction': '지난 카트 보기 버튼',
  'admin.content.save': '저장',
  'admin.content.saving': '저장 중...',
  'admin.carts.filters.searchPlaceholder': 'user / cart',
  'admin.carts.history.table.cart': 'Cart',
  'admin.carts.history.table.items': 'Items',
  'admin.carts.history.table.savedAt': '저장 시각',
  'admin.carts.history.table.total': 'Total',
  'admin.carts.history.table.user': 'User',
  'admin.common.badge.fallback': 'Fallback data',
  'admin.common.badge.live': 'Live data',
  'admin.common.badge.loading': 'Loading...',
  'admin.common.none': 'none',
  'admin.common.notReady': '미완료',
  'admin.common.off': 'OFF',
  'admin.common.on': 'ON',
  'admin.common.ready': '완료',
  'admin.config.branding.adsAssetsDir': 'adsAssetsDir',
  'admin.config.branding.assetsDir': 'brandingAssetsDir',
  'admin.config.branding.homeSubtitle': 'homeSubtitle',
  'admin.config.branding.logoImageUrl': 'logoImageUrl',
  'admin.config.branding.logoText': 'logoText',
  'admin.config.branding.logoType': 'logoType',
  'admin.config.branding.mySubtitle': 'mySubtitle',
  'admin.config.branding.splashImageUrl': 'splashImageUrl',
  'admin.config.branding.title': '브랜딩',
  'admin.config.desc': '런타임 설정',
  'admin.config.kpi.ads': 'Ads',
  'admin.config.kpi.apiBase': 'API Base',
  'admin.config.kpi.apiBaseValue': 'Backend',
  'admin.config.kpi.backendRun': 'Backend Run',
  'admin.config.kpi.backendRunNote': 'launchd direct backend는 비활성화',
  'admin.config.kpi.remoteScan': 'Remote Scan',
  'admin.config.kpi.storage': 'Storage',
  'admin.config.kpi.storageBlocked': 'Blocked',
  'admin.config.kpi.storageWritable': 'Writable',
  'admin.config.storage.errors': 'errors',
  'admin.config.storage.failed': 'failed',
  'admin.config.storage.failureLogs': 'failureLogs',
  'admin.config.storage.feedbackLogs': 'feedbackLogs',
  'admin.config.storage.input': 'input',
  'admin.config.storage.root': 'storageRoot',
  'admin.config.storage.title': 'Storage health',
  'admin.config.storage.writable': 'storageWritable',
  'admin.config.title': 'Config',
  'admin.overview.compare.day': '전일',
  'admin.overview.compare.month': '전월',
  'admin.overview.compare.week': '전주',
  'admin.overview.cumulative.activeUsers': 'Active Users',
  'admin.overview.cumulative.adClicks': 'Ad Clicks',
  'admin.overview.cumulative.adCtr': 'Ad CTR',
  'admin.overview.cumulative.adImpressions': 'Ad Impressions',
  'admin.overview.cumulative.adRow': 'Ad',
  'admin.overview.cumulative.cartSaves': 'Cart Saves',
  'admin.overview.cumulative.clicks': 'Clicks',
  'admin.overview.cumulative.ctr': 'CTR',
  'admin.overview.cumulative.impressions': 'Impressions',
  'admin.overview.cumulative.newUsers': 'New Users',
  'admin.overview.cumulative.scans': 'Scans',
  'admin.overview.cumulative.slot': 'Slot',
  'admin.overview.cumulative.successful': 'Successful',
  'admin.overview.meta.generatedAt': '생성시각',
  'admin.overview.meta.mode': '모드',
  'admin.overview.meta.snapshotDate': '기준일',
  'admin.overview.meta.source': '소스',
  'admin.overview.period.deviceReady': 'device 준비',
  'admin.overview.period.loadFailed': '기간 집계를 불러오지 못했어',
  'admin.overview.period.option.month': '월',
  'admin.overview.period.option.quarter': '분기',
  'admin.overview.period.option.week': '주',
  'admin.overview.period.option.year': '연',
  'admin.overview.period.range': '기간',
  'admin.overview.period.state': '상태',
  'admin.overview.refresh.done': '오늘 스냅샷 갱신 완료',
  'admin.overview.refresh.failed': '스냅샷 갱신 실패',
  'admin.overview.snapshot.activeMembers': 'Active Members',
  'admin.overview.snapshot.adCtr': 'Ad CTR',
  'admin.overview.snapshot.scanSuccess': 'Scan Success',
  'admin.overview.snapshot.totalScans': 'Total Scans',
  'admin.scanops.action.moving': 'moving...',
  'admin.scanops.action.quarantine': 'quarantine',
  'admin.scanops.action.quarantineDone': 'job을 quarantine으로 이동했어',
  'admin.scanops.action.quarantineFailed': 'job quarantine 실패',
  'admin.scanops.action.retry': 'retry',
  'admin.scanops.action.retryDone': 'job이 다시 queue로 들어갔어',
  'admin.scanops.action.retryFailed': 'job retry 실패',
  'admin.scanops.action.retrying': 'retrying...',
  'admin.scanops.failures.table.code': 'Code',
  'admin.scanops.failures.table.job': 'Job',
  'admin.scanops.failures.table.message': 'Message',
  'admin.scanops.failures.table.stage': 'Stage',
  'admin.scanops.failures.table.time': 'Time',
  'admin.scanops.feedback.accepted': 'accepted',
  'admin.scanops.feedback.corrected': 'corrected',
  'admin.scanops.feedback.table.action': 'Action',
  'admin.scanops.feedback.table.job': 'Job',
  'admin.scanops.feedback.table.time': 'Time',
  'admin.scanops.feedback.table.user': 'User',
  'admin.scanops.filter.all': 'All',
  'admin.scanops.filter.done': 'Done',
  'admin.scanops.filter.failed': 'Failed',
  'admin.scanops.filter.quarantined': 'Quarantined',
  'admin.scanops.jobs.desc': '현재 queue 적체와 완료/실패 상태를 본다',
  'admin.scanops.jobs.detail.created': 'Created',
  'admin.scanops.jobs.detail.errorCode': 'Error code',
  'admin.scanops.jobs.detail.errorMessage': 'Error message',
  'admin.scanops.jobs.detail.jobId': 'Job ID',
  'admin.scanops.jobs.detail.status': 'Status',
  'admin.scanops.jobs.detail.updated': 'Updated',
  'admin.scanops.jobs.detail.user': 'User',
  'admin.scanops.jobs.detailDesc': '실패 사유와 상태 갱신 시각을 바로 본다',
  'admin.scanops.jobs.detailEmpty': '선택된 job이 없어',
  'admin.scanops.jobs.detailTitle': 'Selected job detail',
  'admin.scanops.jobs.emptyFiltered': '조건에 맞는 scan job이 없어',
  'admin.scanops.jobs.table.action': 'Action',
  'admin.scanops.jobs.table.created': 'Created',
  'admin.scanops.jobs.table.error': 'Error',
  'admin.scanops.jobs.table.job': 'Job',
  'admin.scanops.jobs.table.status': 'Status',
  'admin.scanops.jobs.table.user': 'User',
  'admin.scanops.jobs.title': 'Recent jobs',
  'admin.scanops.kpi.doneFailed': 'Done / Failed',
  'admin.scanops.kpi.failures': 'Failures',
  'admin.scanops.kpi.failuresNote': 'submit / polling / result / worker',
  'admin.scanops.kpi.feedback': 'Feedback',
  'admin.scanops.kpi.feedbackAccepted': 'accepted',
  'admin.scanops.kpi.feedbackCorrected': 'corrected',
  'admin.scanops.kpi.jobs': 'Jobs',
  'admin.scanops.kpi.jobsNoteProcessing': 'processing',
  'admin.scanops.kpi.jobsNoteQueued': 'queued',
  'admin.scanops.kpi.oldestQueued': 'oldest queued',
  'admin.scanops.kpi.quarantine': 'Quarantined',
  'admin.scanops.kpi.quarantineNote': 'worker 제외 운영 보관',
  'admin.scanops.kpi.queueClear': 'queue clear',
  'admin.scanops.kpi.worker': 'Worker',
  'admin.scanops.kpi.workerNote': 'login-session daemon',
  'admin.scanops.kpi.workerRunning': 'RUNNING',
  'admin.scanops.kpi.workerStopped': 'STOPPED',
  'admin.users.detail.back': 'Users로 돌아가기',
  'admin.users.detail.cleanup.legacyDesc': '이 사용자는 guestKey 없이 남아 있는 legacy guest야. 카트가 있으면 자동 병합하지 않고 운영자가 대상 user id를 지정해서 수동 merge해.',
  'admin.users.detail.cleanup.mergeAction': 'Manual merge 실행',
  'admin.users.detail.cleanup.merging': 'Merging...',
  'admin.users.detail.cleanup.rule1': 'same install/device reuses the same guest user when a stable guest key is present',
  'admin.users.detail.cleanup.rule2': 'guest carts stay linked to that guest user id and preserve save-by-save snapshots',
  'admin.users.detail.cleanup.rule3': 'sign-up/login with the same install key inherits guest history into the member account',
  'admin.users.detail.cleanup.rule4': 'legacy guests without guestKey stay manual-review 대상이다',
  'admin.users.detail.cleanup.targetLabel': 'Target member user id',
  'admin.users.detail.cleanup.targetPlaceholder': 'merge 대상 user id',
  'admin.users.detail.cleanup.title': 'Cleanup policy',
  'admin.users.detail.desc.guest': '게스트 고객 드릴다운',
  'admin.users.detail.desc.member': '고객 저장 이력 드릴다운',
  'admin.users.detail.history.carts': 'carts',
  'admin.users.detail.history.desc': '한 고객의 저장 이력을 날짜별 snapshot으로 본다',
  'admin.users.detail.history.empty': '아직 저장된 카트가 없어',
  'admin.users.detail.history.table.from': 'from',
  'admin.users.detail.history.table.items': 'Items',
  'admin.users.detail.history.table.preview': 'Preview',
  'admin.users.detail.history.table.rootSnapshot': 'root snapshot',
  'admin.users.detail.history.table.savedDate': '저장일',
  'admin.users.detail.history.table.snapshot': 'Snapshot',
  'admin.users.detail.history.table.title': 'Title',
  'admin.users.detail.history.table.total': 'Total',
  'admin.users.detail.history.title': '지난 카트 기록',
  'admin.users.detail.kpi.lastSaved': '최근 저장',
  'admin.users.detail.kpi.totalCarts': 'Total carts',
  'admin.users.detail.kpi.totalItems': 'Total items',
  'admin.users.detail.kpi.totalValue': 'Total value',
  'admin.users.detail.merge.done': 'legacy guest를 대상 user로 merge했어',
  'admin.users.detail.merge.failed': 'legacy guest merge에 실패했어',
  'admin.users.detail.merge.targetRequired': '대상 user id를 입력해',
  'admin.users.detail.profile.created': 'created',
  'admin.users.detail.profile.email': 'Email',
  'admin.users.detail.profile.guestKey': 'Guest key',
  'admin.users.detail.profile.lastAppVersion': 'Last app version',
  'admin.users.detail.profile.lastPlatform': 'Last platform',
  'admin.users.detail.profile.lastSeen': 'last seen',
  'admin.users.detail.profile.mergedAt': 'Merged at',
  'admin.users.detail.profile.mergedInto': 'Merged into',
  'admin.users.detail.profile.provider': 'provider',
  'admin.users.detail.profile.status': 'status',
  'admin.users.detail.profile.title': 'Customer profile',
  'admin.users.detail.profile.type': 'type',
  'admin.users.detail.profile.userId': 'User ID',
  'admin.users.detail.title': 'Customer detail',
  'admin.users.legacy.archiveFailed': 'archive failed',
  'admin.users.legacy.archived': 'archived',
  'admin.users.legacy.table.action': 'Action',
  'admin.users.legacy.table.guest': 'Guest',
  'admin.users.legacy.table.lastActive': 'Last active',
  'admin.users.legacy.table.savedCarts': '저장 카트 수',
  'admin.users.list.desc': 'Current user list',
  'admin.users.list.table.email': 'Email',
  'admin.users.list.table.joined': 'Joined',
  'admin.users.list.table.name': 'Name',
  'admin.users.list.table.type': 'Type',
  'admin.users.list.title': 'Users',
  'admin.users.type.guest': 'guest',
  'admin.users.type.member': 'member',
  'admin.ads.filters.option.all' : '전체',
  'admin.ads.filters.option.live' : '라이브',
  'admin.ads.preview.adSlot' : 'AD SLOT',
  'admin.ads.preview.spec.my.placement' : '계정 카드 아래',
  'admin.ads.preview.spec.my.subtitle' : '계정/혜택 화면',
  'admin.ads.preview.spec.my.title' : 'My',
  'admin.ads.preview.spec.saveComplete.placement' : '요약 아래, 액션 버튼 위',
  'admin.ads.preview.spec.saveComplete.subtitle' : '저장 완료 화면',
  'admin.ads.preview.spec.saveComplete.title' : 'Save Complete',
  'admin.ads.preview.spec.savedFirst.placement' : '첫 카드 다음 위치',
  'admin.ads.preview.spec.savedList.subtitle' : 'My 내부 지난 카트 목록',
  'admin.ads.preview.spec.savedList.title' : '지난 카트 리스트',
  'admin.ads.preview.spec.savedThird.placement' : '세 번째 카드 다음 위치',
  'admin.ads.saveFailed' : '광고 슬롯 저장 실패',
  'admin.ads.status.cancelled' : '취소됨',
  'admin.ads.status.ended' : '종료됨',
  'admin.ads.status.scheduled' : '예약됨',
  'admin.overview.snapshot.mau' : 'MAU',
}
