export const ADMIN_COPY_DEFAULTS: Record<string, string> = {
  'admin.nav.brand': '카트리 운영센터',
  'admin.nav.brandMeta': '운영센터',
  'admin.nav.overview': '대시보드',
  'admin.nav.users': '고객',
  'admin.nav.scanOps': '스캔 운영',
  'admin.nav.carts': '저장 카트',
  'admin.nav.ads': '광고 운영',
  'admin.nav.content': '브랜드·문구',
  'admin.nav.config': '기본 설정',
  'admin.nav.logout': '로그아웃',
  'admin.nav.loggingOut': '정리 중...',
  'admin.common.refresh': '데이터 불러오기',
  'admin.common.refreshing': '불러오는 중...',
  'admin.copy.toggle': '수정 모드',
  'admin.copy.panelTitle': '현재 페이지 문구 수정',
  'admin.copy.panelDesc': '기본 설정을 제외하고, 현재 화면의 고정 문구를 바로 수정한다.',
  'admin.copy.save': '문구 저장',
  'admin.copy.saving': '저장 중...',
  'admin.copy.cancel': '취소',
  'admin.copy.saved': '문구 저장 완료',
  'admin.copy.saveFailed': '문구 저장 실패',
  'admin.copy.empty': '이 페이지에 등록된 문구가 아직 없어',
  'admin.copy.field.common': '공통',
  'admin.copy.field.page': '페이지',
  'admin.login.eyebrow': '운영 보호',
  'admin.login.title': '비밀번호 확인',
  'admin.login.desc': '관리자 비밀번호 입력',
  'admin.login.passwordLabel': '관리자 비밀번호',
  'admin.login.passwordPlaceholder': '비밀번호 입력',
  'admin.login.submit': '들어가기',
  'admin.login.submitting': '확인 중...',
  'admin.login.error.expired': '세션이 만료됐거나 비밀번호가 바뀌었어. 다시 로그인해.',
  'admin.login.error.invalid': '비밀번호가 맞지 않아. 다시 확인해.',
  'admin.login.error.failed': '로그인에 실패했어',
  'admin.overview.title': '대시보드',
  'admin.overview.desc': '핵심 지표',
  'admin.overview.snapshot.data': '데이터',
  'admin.overview.snapshot.scan': '스캔',
  'admin.overview.snapshot.members': '회원',
  'admin.overview.snapshot.ad': '광고',
  'admin.overview.cumulative.users': '고객',
  'admin.overview.cumulative.scan': '스캔',
  'admin.overview.cumulative.ad': '광고',
  'admin.overview.period.title': '누적 보기',
  'admin.overview.period.desc': '선택 기간 누적 값',
  'admin.users.title': '고객',
  'admin.users.desc': '고객 목록',
  'admin.users.legacy.title': '레거시 비회원 정리',
  'admin.users.legacy.desc': '자동 병합 없이 운영 검토 대상을 모아둔 목록',
  'admin.users.legacy.empty': '정리 대상 비회원 없음',
  'admin.users.legacy.archive': '보관',
  'admin.users.legacy.archiving': '처리 중...',
  'admin.users.legacy.merge': '통합 검토',
  'admin.scanops.title': '스캔 운영',
  'admin.scanops.desc': '작업 상태와 피드백·실패 흐름',
  'admin.scanops.feedback.title': '최근 피드백',
  'admin.scanops.feedback.desc': '사용자 수락 여부와 수정 반영 여부',
  'admin.scanops.feedback.empty': '피드백 로그 없음',
  'admin.scanops.failures.title': '최근 실패',
  'admin.scanops.failures.desc': '제출 / 처리 / 폴링 / 결과 단계 실패',
  'admin.scanops.failures.empty': '실패 로그 없음',
  'admin.carts.title': '저장 카트',
  'admin.carts.desc': '고객별 저장 카트 히스토리',
  'admin.carts.filters.title': '필터',
  'admin.carts.filters.desc': '고객/날짜 기준으로 조회하고 같은 조건으로 다운로드',
  'admin.carts.filters.downloadXlsx': 'Excel(.xlsx) 다운로드',
  'admin.carts.filters.downloadCsv': 'CSV 다운로드',
  'admin.carts.filters.reset': '초기화',
  'admin.carts.filters.apply': '필터 적용',
  'admin.carts.history.title': '저장 카트 히스토리',
  'admin.carts.history.desc': 'snapshot lineage와 저장 시점별 상품 구성을 함께 본다',
  'admin.carts.history.empty': '조건에 맞는 저장 카트가 없어',
  'admin.ads.title': '광고 운영',
  'admin.ads.desc': '광고 슬롯과 배너 자산 관리',
  'admin.ads.filters.title': '지난 광고 필터',
  'admin.ads.filters.desc': '유형/상태/검색어와 기간으로 지난 광고를 좁혀보고, 같은 조건으로 일괄 다운로드',
  'admin.ads.filters.search': '검색',
  'admin.ads.filters.variant': '유형',
  'admin.ads.filters.status': '상태',
  'admin.ads.filters.periodFrom': '시작일',
  'admin.ads.filters.periodTo': '종료일',
  'admin.ads.filters.bulkExport': '기간내 지난광고 Excel 일괄 다운로드',
  'admin.ads.history.title': '지난 광고 데이터',
  'admin.ads.history.desc': '이 슬롯에 연결되었던 지난 광고 성과 기록',
  'admin.ads.history.empty': '조건에 맞는 지난 광고가 없어',
  'admin.ads.livePanel.title': '현재 노출 광고',
  'admin.ads.livePanel.desc': '현재 앱에 노출 중인 광고 설정',
  'admin.ads.livePanel.save': '현재 광고 저장',
  'admin.ads.reservedPanel.title': '예약 광고 세팅',
  'admin.ads.reservedPanel.desc': '다음 노출 순서를 미리 준비하는 예약 광고 설정',
  'admin.ads.reservedPanel.save': '예약 광고 저장',
  'admin.ads.preview.title': '노출 위치 미리보기',
  'admin.ads.preview.empty': '이 슬롯용 미리보기가 아직 준비되지 않았어',
  'admin.ads.saving': '저장 중...',
  'admin.ads.uploading': '업로드 중...',
  'admin.ads.upload.liveDone': '현재',
  'admin.ads.upload.reservedDone': '예약',
  'admin.ads.upload.doneSuffix': '배너 업로드 완료',
  'admin.ads.fields.status': '상태',
  'admin.ads.fields.slotLabel': '슬롯 이름',
  'admin.ads.fields.slotDescription': '슬롯 설명',
  'admin.ads.fields.placementNote': '노출 위치 설명',
  'admin.ads.fields.title': '제목',
  'admin.ads.fields.message': '문구',
  'admin.ads.fields.cta': 'CTA',
  'admin.ads.fields.link': '링크',
  'admin.ads.fields.exposureWindow': '노출 기간',
  'admin.ads.fields.reservationWindow': '예약 기간',
  'admin.ads.fields.exposureStart': '노출 시작',
  'admin.ads.fields.exposureEnd': '노출 종료',
  'admin.ads.fields.reservationStart': '예약 시작',
  'admin.ads.fields.reservationEnd': '예약 종료',
  'admin.ads.fields.assetUpload': '배너 업로드',
  'admin.ads.fields.assetSelect': '배너 파일 선택',
  'admin.ads.fields.liveAssetDesc': '현재 노출 배너 자산',
  'admin.ads.fields.reservedAssetDesc': '예약용 배너 자산',
  'admin.ads.fields.connected': '연결됨:',
  'admin.ads.history.table.title': '광고명',
  'admin.ads.history.table.variant': '유형',
  'admin.ads.history.table.status': '상태',
  'admin.ads.history.table.period': '기간',
  'admin.ads.history.table.impressions': 'Impressions',
  'admin.ads.history.table.clicks': 'Clicks',
  'admin.ads.history.table.ctr': 'CTR',
  'admin.ads.history.table.image': '이미지',
  'admin.ads.history.table.download': '다운로드',
  'admin.ads.history.variant.live': '현재 광고 이력',
  'admin.ads.history.variant.reserved': '예약 광고 이력',
  'admin.ads.history.noMessage': '메시지 없음',
  'admin.ads.history.downloadSingle': 'Excel 다운로드',
  'admin.content.title': 'Content',
  'admin.content.desc': '앱 문구와 로고 관리',
  'admin.content.assets.title': '브랜드 자산',
  'admin.content.preview.title': '프리뷰',
  'admin.content.preview.splash': 'Splash',
  'admin.content.preview.noSplash': '등록된 스플래시 이미지 없음',
  'admin.content.preview.login': '로그인 화면',
  'admin.content.guide.title': '업로드 가이드',
  'admin.content.guide.logo': '로고: PNG, JPG, WEBP, SVG',
  'admin.content.guide.splash': '스플래시: PNG, JPG, WEBP',
  'admin.content.guide.size': '최대 용량: 8MB 이하',
  'admin.content.guide.save': '저장해야 앱 설정에 반영돼',
  'admin.content.loadFailed': '브랜딩 데이터를 불러오지 못했어',
  'admin.content.saveDone': '브랜딩 설정 저장 완료',
  'admin.content.saveFailed': '브랜딩 저장 실패',
  'admin.content.uploadFailed': '이미지 업로드 실패',
  'admin.content.upload.logoDone': '로고 업로드 완료',
  'admin.content.upload.splashDone': '스플래시 이미지 업로드 완료',
  'admin.content.uploading': '업로드 중...',
  'admin.content.fields.logoType': '로고 타입',
  'admin.content.fields.logoUpload': '로고 업로드',
  'admin.content.fields.logoUploadSelect': '로고 파일 선택',
  'admin.content.fields.logoUploadDesc': '직접 업로드해서 바로 연결',
  'admin.content.fields.splashUpload': '스플래시 이미지 업로드',
  'admin.content.fields.splashUploadSelect': '스플래시 파일 선택',
  'admin.content.fields.splashUploadDesc': '앱 시작 화면용 이미지 등록',
  'admin.content.fields.connected': '연결됨:',
  'admin.content.groups.branding.title': '기본 브랜딩',
  'admin.content.groups.branding.desc': '로고 모드와 탭 라벨',
  'admin.content.groups.savedHome.title': '지난 카트 / Home 카피',
  'admin.content.groups.savedHome.desc': '홈과 My 내부 지난 카트 문구',
  'admin.content.groups.help.title': '도움 탭 카피',
  'admin.content.groups.help.desc': '중간 도움 탭 문구',
  'admin.content.groups.myLogin.title': 'My / 로그인 카피',
  'admin.content.groups.myLogin.desc': '로그인과 My 화면 문구',
  'admin.content.groups.saveComplete.title': '저장 완료 카피',
  'admin.content.groups.saveComplete.desc': '저장 완료 문구',
  'admin.content.fields.logoText': '로고 텍스트',
  'admin.content.fields.homeTabLabel': 'Home 탭 라벨',
  'admin.content.fields.helpTabLabel': '도움 탭 라벨',
  'admin.content.fields.myTabLabel': 'My 탭 라벨',
  'admin.content.fields.helpPageTitle': '도움 페이지 제목',
  'admin.content.fields.helpSubtitle': '도움 subtitle',
  'admin.content.fields.homeRecentSavedAction': '지난 카트 보기 버튼',
  'admin.content.fields.savedPageTitle': '지난 카트 섹션 제목',
  'admin.content.fields.homeSubtitle': 'Home subtitle',
  'admin.content.fields.savedSubtitle': '지난 카트 설명',
  'admin.content.fields.savedEmptyTitle': '지난 카트 empty 제목',
  'admin.content.fields.savedEmptyBody': '지난 카트 empty 설명',
  'admin.content.fields.recentSavedTitle': '최근 저장 카트 제목',
  'admin.content.fields.recentSavedEmptyBody': '최근 저장 카트 empty 설명',
  'admin.content.fields.myPageTitle': 'My 페이지 제목',
  'admin.content.fields.mySubtitle': 'My subtitle',
  'admin.content.fields.myBenefitsTitle': 'My benefits 제목',
  'admin.content.fields.myBenefitsBody': 'My benefits 설명',
  'admin.content.fields.loginPageTitle': '로그인 페이지 제목',
  'admin.content.fields.loginSubtitle': 'Login subtitle',
  'admin.content.fields.loginBenefitsTitle': '로그인 benefits 제목',
  'admin.content.fields.loginBenefitsBody': '로그인 benefits 설명',
  'admin.content.fields.drawerGuestTitle': 'Drawer guest 제목',
  'admin.content.fields.drawerGuestBody': 'Drawer guest 설명',
  'admin.content.fields.saveCompleteTitle': '저장 완료 제목',
  'admin.content.fields.saveCompleteSubtitle': '저장 완료 부제',
  'admin.content.fields.saveCompleteViewSavedAction': '지난 카트 보기 버튼',
  'admin.content.save': '저장',
  'admin.content.saving': '저장 중...',
  'admin.carts.filters.searchPlaceholder': '고객 / 카트',
  'admin.carts.history.table.cart': '카트',
  'admin.carts.history.table.items': '상품수',
  'admin.carts.history.table.savedAt': '저장 시각',
  'admin.carts.history.table.total': '합계',
  'admin.carts.history.table.user': '고객',
  'admin.common.badge.fallback': '대체 데이터',
  'admin.common.badge.live': '실데이터',
  'admin.common.badge.loading': '불러오는 중...',
  'admin.common.none': '없음',
  'admin.common.notReady': '미완료',
  'admin.common.off': '중지',
  'admin.common.on': '사용',
  'admin.common.ready': '완료',
  'admin.config.branding.adsAssetsDir': '광고 자산 경로',
  'admin.config.branding.assetsDir': '브랜드 자산 경로',
  'admin.config.branding.homeSubtitle': '홈 부제',
  'admin.config.branding.logoImageUrl': '로고 이미지 URL',
  'admin.config.branding.logoText': '로고 문구',
  'admin.config.branding.logoType': '로고 유형',
  'admin.config.branding.mySubtitle': '마이 부제',
  'admin.config.branding.splashImageUrl': '스플래시 이미지 URL',
  'admin.config.branding.title': '브랜딩',
  'admin.config.desc': '런타임 설정',
  'admin.config.kpi.ads': '광고',
  'admin.config.kpi.apiBase': 'API 기준 주소',
  'admin.config.kpi.apiBaseValue': '백엔드',
  'admin.config.kpi.backendRun': '백엔드 실행',
  'admin.config.kpi.backendRunNote': 'launchd 직접 백엔드는 비활성화',
  'admin.config.kpi.remoteScan': '원격 스캔',
  'admin.config.kpi.storage': '저장 공간',
  'admin.config.kpi.storageBlocked': '막힘',
  'admin.config.kpi.storageWritable': '정상',
  'admin.config.storage.errors': '오류',
  'admin.config.storage.failed': '실패',
  'admin.config.storage.failureLogs': '실패 로그',
  'admin.config.storage.feedbackLogs': '피드백 로그',
  'admin.config.storage.input': '입력',
  'admin.config.storage.root': '저장 경로',
  'admin.config.storage.title': '저장 공간 상태',
  'admin.config.storage.writable': '쓰기 가능',
  'admin.config.title': '기본 설정',
  'admin.overview.compare.day': '전일',
  'admin.overview.compare.month': '전월',
  'admin.overview.compare.week': '전주',
  'admin.overview.cumulative.activeUsers': '활성 고객',
  'admin.overview.cumulative.adClicks': '광고 클릭',
  'admin.overview.cumulative.adCtr': '광고 클릭률',
  'admin.overview.cumulative.adImpressions': '광고 노출',
  'admin.overview.cumulative.adRow': '광고',
  'admin.overview.cumulative.cartSaves': '카트 저장',
  'admin.overview.cumulative.clicks': '클릭',
  'admin.overview.cumulative.ctr': '클릭률',
  'admin.overview.cumulative.impressions': '노출',
  'admin.overview.cumulative.newUsers': '신규 고객',
  'admin.overview.cumulative.scans': '스캔',
  'admin.overview.cumulative.slot': '광고 위치',
  'admin.overview.cumulative.successful': '성공',
  'admin.overview.meta.generatedAt': '생성 시각',
  'admin.overview.meta.mode': '모드',
  'admin.overview.meta.snapshotDate': '기준일',
  'admin.overview.meta.source': '소스',
  'admin.overview.period.deviceReady': '기기 준비',
  'admin.overview.period.loadFailed': '기간 집계를 불러오지 못했어',
  'admin.overview.period.option.month': '월',
  'admin.overview.period.option.quarter': '분기',
  'admin.overview.period.option.week': '주',
  'admin.overview.period.option.year': '연',
  'admin.overview.period.range': '기간',
  'admin.overview.period.state': '상태',
  'admin.overview.refresh.done': '오늘 스냅샷 갱신 완료',
  'admin.overview.refresh.failed': '스냅샷 갱신 실패',
  'admin.overview.snapshot.activeMembers': '활성 회원',
  'admin.overview.snapshot.adClicks': '광고 클릭',
  'admin.overview.snapshot.adCtr': '광고 클릭률',
  'admin.overview.snapshot.adImpressions': '광고 노출',
  'admin.overview.snapshot.cartSaveRate': '카트 저장률',
  'admin.overview.snapshot.guestProfiles': '비회원',
  'admin.overview.snapshot.guestToMemberConversion': '비회원 전환률',
  'admin.overview.snapshot.scanSuccess': '스캔 성공률',
  'admin.overview.snapshot.totalScans': '총 스캔',
  'admin.scanops.action.moving': '이동 중...',
  'admin.scanops.action.quarantine': '격리',
  'admin.scanops.action.quarantineDone': '작업을 격리로 이동했어',
  'admin.scanops.action.quarantineFailed': '격리 이동 실패',
  'admin.scanops.action.retry': '재실행',
  'admin.scanops.action.retryDone': '작업을 다시 대기열로 보냈어',
  'admin.scanops.action.retryFailed': '재실행 실패',
  'admin.scanops.action.retrying': '재실행 중...',
  'admin.scanops.failures.table.code': '오류 코드',
  'admin.scanops.failures.table.job': '작업',
  'admin.scanops.failures.table.message': '오류 내용',
  'admin.scanops.failures.table.stage': '단계',
  'admin.scanops.failures.table.time': '시각',
  'admin.scanops.feedback.accepted': '수락',
  'admin.scanops.feedback.corrected': '수정',
  'admin.scanops.feedback.table.action': '처리',
  'admin.scanops.feedback.table.job': '작업',
  'admin.scanops.feedback.table.time': '시각',
  'admin.scanops.feedback.table.user': '고객',
  'admin.scanops.filter.all': '전체',
  'admin.scanops.filter.done': '완료',
  'admin.scanops.filter.failed': '실패',
  'admin.scanops.filter.quarantined': '격리',
  'admin.scanops.jobs.desc': '현재 대기열과 완료·실패 상태',
  'admin.scanops.jobs.detail.created': '생성 시각',
  'admin.scanops.jobs.detail.errorCode': '오류 코드',
  'admin.scanops.jobs.detail.errorMessage': '오류 내용',
  'admin.scanops.jobs.detail.jobId': '작업 ID',
  'admin.scanops.jobs.detail.status': '상태',
  'admin.scanops.jobs.detail.updated': '수정 시각',
  'admin.scanops.jobs.detail.user': '고객',
  'admin.scanops.jobs.detailDesc': '실패 사유와 상태 갱신 시각',
  'admin.scanops.jobs.detailEmpty': '선택된 작업 없음',
  'admin.scanops.jobs.detailTitle': '작업 상세',
  'admin.scanops.jobs.emptyFiltered': '조건에 맞는 작업 없음',
  'admin.scanops.jobs.table.action': '동작',
  'admin.scanops.jobs.table.created': '생성 시각',
  'admin.scanops.jobs.table.error': '오류',
  'admin.scanops.jobs.table.job': '작업',
  'admin.scanops.jobs.table.status': '상태',
  'admin.scanops.jobs.table.user': '고객',
  'admin.scanops.jobs.title': '최근 작업',
  'admin.scanops.kpi.doneFailed': '완료 / 실패',
  'admin.scanops.kpi.failures': '실패',
  'admin.scanops.kpi.failuresNote': '제출 / 폴링 / 결과 / 작업기',
  'admin.scanops.kpi.feedback': '피드백',
  'admin.scanops.kpi.feedbackAccepted': '수락',
  'admin.scanops.kpi.feedbackCorrected': '수정',
  'admin.scanops.kpi.jobs': '작업',
  'admin.scanops.kpi.jobsNoteProcessing': '처리중',
  'admin.scanops.kpi.jobsNoteQueued': '대기',
  'admin.scanops.kpi.oldestQueued': '최장 대기',
  'admin.scanops.kpi.quarantine': '격리',
  'admin.scanops.kpi.quarantineNote': '작업기 제외 운영 보관',
  'admin.scanops.kpi.queueClear': '대기열 정상',
  'admin.scanops.kpi.worker': '작업기',
  'admin.scanops.kpi.workerNote': '로그인 세션 데몬',
  'admin.scanops.kpi.workerRunning': '동작',
  'admin.scanops.kpi.workerStopped': '중지',
  'admin.users.detail.back': '고객으로 돌아가기',
  'admin.users.detail.cleanup.legacyDesc': '이 고객은 guestKey 없이 남아 있는 레거시 비회원이야. 카트가 있으면 자동 병합하지 않고 운영자가 대상 회원 ID를 지정해 수동 통합해.',
  'admin.users.detail.cleanup.mergeAction': '수동 통합 실행',
  'admin.users.detail.cleanup.merging': '통합 중...',
  'admin.users.detail.cleanup.rule1': '안정적인 guest key가 있으면 같은 설치와 기기에서 같은 비회원 ID를 재사용',
  'admin.users.detail.cleanup.rule2': '비회원 카트는 해당 비회원 ID에 연결된 채 저장본 이력을 유지',
  'admin.users.detail.cleanup.rule3': '같은 설치 키로 가입 또는 로그인하면 비회원 이력을 회원 계정으로 승계',
  'admin.users.detail.cleanup.rule4': 'guestKey 없는 레거시 비회원은 수동 검토 유지',
  'admin.users.detail.cleanup.targetLabel': '대상 회원 ID',
  'admin.users.detail.cleanup.targetPlaceholder': '통합 대상 회원 ID',
  'admin.users.detail.cleanup.title': '정리 기준',
  'admin.users.detail.desc.guest': '비회원 상세',
  'admin.users.detail.desc.member': '고객 저장 이력 상세',
  'admin.users.detail.history.carts': '카트',
  'admin.users.detail.history.desc': '한 고객의 저장 이력',
  'admin.users.detail.history.empty': '저장된 카트 없음',
  'admin.users.detail.history.table.from': '출처',
  'admin.users.detail.history.table.items': '상품수',
  'admin.users.detail.history.table.preview': '미리보기',
  'admin.users.detail.history.table.rootSnapshot': '원본 저장본',
  'admin.users.detail.history.table.savedDate': '저장일',
  'admin.users.detail.history.table.snapshot': '저장본',
  'admin.users.detail.history.table.title': '제목',
  'admin.users.detail.history.table.total': '합계',
  'admin.users.detail.history.title': '지난 카트 기록',
  'admin.users.detail.kpi.lastSaved': '최근 저장',
  'admin.users.detail.kpi.totalCarts': '총 카트',
  'admin.users.detail.kpi.totalItems': '총 상품수',
  'admin.users.detail.kpi.totalValue': '총 금액',
  'admin.users.detail.merge.done': '레거시 비회원을 대상 회원으로 통합했어',
  'admin.users.detail.merge.failed': '레거시 비회원 통합 실패',
  'admin.users.detail.merge.targetRequired': '대상 회원 ID를 입력해',
  'admin.users.detail.profile.created': '생성 시각',
  'admin.users.detail.profile.email': '이메일',
  'admin.users.detail.profile.guestKey': '비회원 키',
  'admin.users.detail.profile.lastAppVersion': '최근 앱 버전',
  'admin.users.detail.profile.lastPlatform': '최근 플랫폼',
  'admin.users.detail.profile.lastSeen': '최근 방문',
  'admin.users.detail.profile.mergedAt': '통합 시각',
  'admin.users.detail.profile.mergedInto': '통합 대상',
  'admin.users.detail.profile.provider': '연동 수단',
  'admin.users.detail.profile.status': '상태',
  'admin.users.detail.profile.title': '고객 프로필',
  'admin.users.detail.profile.type': '유형',
  'admin.users.detail.profile.userId': '고객 ID',
  'admin.users.detail.title': '고객 상세',
  'admin.users.legacy.archiveFailed': '보관 실패',
  'admin.users.legacy.archived': '보관 완료',
  'admin.users.legacy.table.action': '동작',
  'admin.users.legacy.table.guest': '비회원',
  'admin.users.legacy.table.lastActive': '최근 방문',
  'admin.users.legacy.table.savedCarts': '저장 카트 수',
  'admin.users.list.desc': '현재 고객 목록',
  'admin.users.list.table.email': '이메일',
  'admin.users.list.table.joined': '가입일',
  'admin.users.list.table.name': '이름',
  'admin.users.list.table.type': '유형',
  'admin.users.list.title': '고객',
  'admin.users.type.guest': '비회원',
  'admin.users.type.member': '회원',
  'admin.ads.filters.option.all' : '전체',
  'admin.ads.filters.option.live' : '라이브',
  'admin.ads.preview.adSlot' : 'AD SLOT',
  'admin.ads.preview.spec.my.placement' : '계정 카드 아래',
  'admin.ads.preview.spec.my.subtitle' : '계정/혜택 화면',
  'admin.ads.preview.spec.my.title' : '마이',
  'admin.ads.preview.spec.saveComplete.placement' : '요약 아래, 액션 버튼 위',
  'admin.ads.preview.spec.saveComplete.subtitle' : '저장 완료 화면',
  'admin.ads.preview.spec.saveComplete.title' : 'Save Complete',
  'admin.ads.preview.spec.savedFirst.placement' : '첫 카드 다음 위치',
  'admin.ads.preview.spec.savedList.subtitle' : 'My 내부 지난 카트 목록',
  'admin.ads.preview.spec.savedList.title' : '지난 카트 리스트',
  'admin.ads.preview.spec.savedThird.placement' : '세 번째 카드 다음 위치',
  'admin.ads.saveFailed' : '광고 슬롯 저장 실패',
  'admin.ads.status.cancelled' : '취소됨',
  'admin.ads.status.ended' : '종료됨',
  'admin.ads.status.scheduled' : '예약됨',
  'admin.overview.snapshot.mau' : 'MAU',
}
