import { CARTLY_PUBLIC_ADMIN_BASE_URL, CARTLY_PUBLIC_APP_BASE_URL } from './publicUrlConfig'

const MOCK_TIMESTAMP = '2026-03-23T00:00:00.000Z'

export const mockSummary = {
  dau: 128,
  wau: 602,
  mau: 1820,
  comparisons: {
    dau: { day: 120, week: 116, month: 109 },
    wau: { day: 590, week: 564, month: 521 },
    mau: { day: 1792, week: 1748, month: 1684 },
  },
  activeUsers: 941,
  newUsers: 214,
  guestToMemberConversion: 0.124,
  totalScans: 4821,
  scanSuccessRate: 0.71,
  cartSaveRate: 0.43,
  adImpressions: 1320,
  adClicks: 48,
  adCtr: 0.036,
  snapshotDate: '2026-03-23',
  snapshotGeneratedAt: '2026-03-23T00:00:00.000Z',
  snapshotSource: 'scheduled',
  dataMode: 'snapshot',
  lifecycle: {
    guestProfiles: 420,
    trackedGuests: 188,
    legacyGuests: 12,
    legacyGuestsWithCarts: 3,
    activeMembers: 154,
    memberUsersWithSavedCarts: 91,
    memberSavedCarts: 268,
    avgSavedCartsPerMember: 2.95,
    guestToMemberConversions: 96,
    guestToMemberConversionRate: 0.229,
    topMembers: [
      {
        userId: 'usr_002',
        displayName: 'Seungdae',
        email: 'ceo@cartly.app',
        cartCount: 12,
        totalValue: 482000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
      {
        userId: 'usr_010',
        displayName: 'Power saver',
        email: 'member10@cartly.app',
        cartCount: 9,
        totalValue: 231000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
    ],
  },
}

export const mockPeriodSummary = {
  period: 'month',
  rangeStart: '2026-03-01',
  rangeEnd: '2026-03-23',
  activeUsers: 941,
  newUsers: 214,
  guestUsers: 160,
  memberUsers: 54,
  guestToMemberConversion: 0.252,
  totalScans: 4821,
  successfulScans: 3423,
  scanSuccessRate: 0.71,
  cartSaves: 2073,
  cartSaveRate: 0.43,
  adImpressions: 1320,
  adClicks: 48,
  adCtr: 0.036,
  adSlots: [
    { slotKey: 'save_complete_sheet_1', impressions: 420, clicks: 16, ctr: 0.0381 },
    { slotKey: 'saved_inline_1', impressions: 360, clicks: 14, ctr: 0.0389 },
    { slotKey: 'saved_inline_2', impressions: 280, clicks: 9, ctr: 0.0321 },
    { slotKey: 'my_perks_inline_1', impressions: 260, clicks: 9, ctr: 0.0346 },
  ],
  deviceBreakdownReady: true,
  lifecycle: {
    guestProfiles: 88,
    trackedGuests: 74,
    legacyGuests: 14,
    legacyGuestsWithCarts: 2,
    activeMembers: 54,
    memberUsersWithSavedCarts: 31,
    memberSavedCarts: 96,
    avgSavedCartsPerMember: 3.1,
    guestToMemberConversions: 19,
    guestToMemberConversionRate: 0.216,
    topMembers: [
      {
        userId: 'usr_002',
        displayName: 'Seungdae',
        email: 'ceo@cartly.app',
        cartCount: 4,
        totalValue: 122000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
      {
        userId: 'usr_010',
        displayName: 'Power saver',
        email: 'member10@cartly.app',
        cartCount: 3,
        totalValue: 88000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
    ],
  },
}

export const mockUsers = [
  {
    id: 'usr_001',
    displayName: 'Guest shopper',
    email: null,
    provider: 'guest',
    isGuest: true,
    guestKey: 'guest-ios-install-001',
    lastDevicePlatform: 'ios',
    lastAppVersion: '0.1.0',
    createdAt: MOCK_TIMESTAMP,
    lastSeenAt: MOCK_TIMESTAMP,
  },
  {
    id: 'usr_002',
    displayName: 'Seungdae',
    email: 'ceo@cartly.app',
    provider: 'google',
    isGuest: false,
    guestKey: null,
    lastDevicePlatform: 'ios',
    lastAppVersion: '0.1.0',
    createdAt: MOCK_TIMESTAMP,
    lastSeenAt: MOCK_TIMESTAMP,
  },
]

export const mockScanJobs = {
  summary: {
    jobsTotal: 2,
    feedbackTotal: 6,
    feedbackAccepted: 4,
    feedbackCorrected: 2,
    failureLogs: 3,
  },
  jobs: [
    {
      id: 'job_001',
      userId: 'usr_002',
      status: 'done',
      errorCode: null,
      errorMessage: null,
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
      startedAt: MOCK_TIMESTAMP,
      finishedAt: MOCK_TIMESTAMP,
      imageAvailable: false,
      imagePathLabel: 'job_001.jpg',
      customerMessage: '신뢰도가 높은 결과예요. 빠르게 확인하고 담아주세요.',
      result: {
        name: 'KIRKLAND SIGNATURE 유아용 물티슈 100매 X 9',
        price: 27990,
        sku: '1212100',
        confidence: 0.98,
        source: 'openclaw-agent',
        rawText: '1212100 KIRKLAND SIGNATURE 유아용 물티슈 100매 X 9 27,990원',
      },
      resultPayload: {
        jobId: 'job_001',
        status: 'done',
        result: {
          name: 'KIRKLAND SIGNATURE 유아용 물티슈 100매 X 9',
          price: 27990,
          sku: '1212100',
          confidence: 0.98,
          source: 'openclaw-agent',
          rawText: '1212100 KIRKLAND SIGNATURE 유아용 물티슈 100매 X 9 27,990원',
        },
        meta: {
          engine: 'openclaw',
          runner: 'openclaw-agent-cli',
        },
      },
      latestFailure: null,
      latestFeedback: {
        id: 'fb_001',
        accepted: true,
        createdAt: MOCK_TIMESTAMP,
        original: {
          name: 'KIRKLAND SIGNATURE 유아용 물티슈 100매 X 9',
          price: 27990,
        },
        corrected: null,
      },
    },
    {
      id: 'job_002',
      userId: null,
      status: 'failed',
      errorCode: 'OCR_NOT_CONFIDENT',
      errorMessage: 'OpenClaw scan runner가 비정상 종료됐어',
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
      startedAt: MOCK_TIMESTAMP,
      finishedAt: MOCK_TIMESTAMP,
      imageAvailable: false,
      imagePathLabel: 'job_002.jpg',
      customerMessage: '사진을 다시 찍거나 직접 추가해 주세요',
      result: null,
      resultPayload: null,
      latestFailure: {
        id: 'fail_001',
        stage: 'openclaw',
        errorCode: 'OPENCLAW_COMMAND_FAILED',
        errorMessage: 'OpenClaw scan runner가 비정상 종료됐어',
        createdAt: MOCK_TIMESTAMP,
        details: {
          stderr: "{'ok': False, 'error': {'code': 'LOW_CONFIDENCE', 'message': '상품명/가격을 충분히 확정하지 못했어'}}",
        },
      },
      latestFeedback: null,
    },
  ],
}

export const mockCarts = {
  summary: {
    totalCarts: 12,
    memberCarts: 7,
    guestCarts: 3,
    anonymousCarts: 2,
    avgCartValue: 42800,
    avgItemCount: 4.2,
  },
  carts: [
    {
      id: 'cart_001',
      userId: 'usr_002',
      sourceCartId: null,
      title: '코스트코 주말 장보기',
      status: 'saved',
      savedDate: '2026-03-23',
      totalPrice: 68400,
      totalCount: 5,
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
      user: {
        id: 'usr_002',
        displayName: 'Seungdae',
        email: 'ceo@cartly.app',
        isGuest: false,
        provider: 'google',
      },
      items: [
        { id: 'item_001', name: '계란 30구', price: 8900, quantity: 1, source: 'manual', scanResultId: null },
        { id: 'item_002', name: '닭가슴살', price: 14900, quantity: 2, source: 'scan', scanResultId: 'job_001' },
      ],
    },
    {
      id: 'cart_002',
      userId: 'usr_001',
      sourceCartId: 'cart_001',
      title: null,
      status: 'saved',
      savedDate: '2026-03-24',
      totalPrice: 21900,
      totalCount: 2,
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
      user: {
        id: 'usr_001',
        displayName: 'Guest shopper',
        email: null,
        isGuest: true,
        provider: 'guest',
      },
      items: [
        { id: 'item_003', name: '우유', price: 4900, quantity: 1, source: 'manual', scanResultId: null },
        { id: 'item_004', name: '시리얼', price: 17000, quantity: 1, source: 'manual', scanResultId: null },
      ],
    },
  ],
}

export const mockSlots = [
  {
    id: 'slot_001',
    slotKey: 'save_complete_sheet_1',
    placementType: 'bottom_sheet',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 88,
      screen: 'save_complete',
      position: 'after_summary_before_actions',
      tone: 'benefit_native',
      title: '다음 장보기도 더 가볍게',
      message: '저장한 카트를 기준으로 혜택 상품을 이어서 볼 수 있어요.',
      ctaLabel: '혜택 보기',
      targetUrl: null,
      imageUrl: null,
    },
  },
  {
    id: 'slot_002',
    slotKey: 'saved_inline_1',
    placementType: 'inline',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 104,
      screen: 'saved_list',
      position: 'after_first_card',
      tone: 'benefit_native',
      title: '지금 많이 담는 상품',
      message: 'Saved 카트와 같이 보는 추천 배너 슬롯이야.',
      ctaLabel: '자세히',
      targetUrl: null,
      imageUrl: null,
    },
  },
  {
    id: 'slot_003',
    slotKey: 'saved_inline_2',
    placementType: 'inline',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 104,
      screen: 'saved_list',
      position: 'after_third_card',
      tone: 'benefit_native',
      title: '같이 담기 좋은 상품',
      message: 'Saved 리스트 중간 보조 프로모션 슬롯이야.',
      ctaLabel: '확인',
      targetUrl: null,
      imageUrl: null,
    },
  },
  {
    id: 'slot_004',
    slotKey: 'my_perks_inline_1',
    placementType: 'inline',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 96,
      screen: 'my',
      position: 'below_account_card',
      tone: 'soft_promo',
      title: '멤버 혜택 확인',
      message: 'My 화면용 보조 배너 슬롯이야.',
      ctaLabel: '보기',
      targetUrl: null,
      imageUrl: null,
    },
  },
]

export const mockBranding = {
  logoType: 'text',
  logoText: 'Cartly',
  logoImageUrl: null,
  splashImageUrl: null,
  loginHeroImageUrl: null,
  homeTabLabel: '홈',
  helpTabLabel: '탐색',
  myTabLabel: '마이',
}

export const mockContentSettings = {
  logoType: 'text',
  logoText: 'Cartly',
  logoImageUrl: null,
  splashImageUrl: null,
  loginHeroImageUrl: null,
  homeTabLabel: '홈',
  helpTabLabel: '탐색',
  myTabLabel: '마이',
  homePageTitle: 'Cartly',
  helpPageTitle: '탐색',
  savedPageTitle: '지난 카트',
  myPageTitle: '마이',
  homeSubtitle: '지금 담은 상품과 합계를 한눈에 확인해보세요',
  helpSubtitle: '지금 필요한 비교만 모아 보여드릴게요',
  homeRecentScanTitle: '최근 스캔',
  homeRecentScanSubtitle: '방금 읽은 상품이에요',
  homeAddSectionTitle: '새 상품 추가',
  homeAddSectionSubtitle: '스캔하거나 직접 담아보세요',
  homeCurrentCartTitle: '현재 카트',
  homeCurrentCartSubtitle: '지금 담은 상품과 합계를 확인해보세요',
  homeCurrentCartEmpty: '아직 담은 상품이 없어요',
  homeAddToCurrentCartDone: '현재 카트에 담았어요',
  homeAddToCurrentCartButton: '현재 카트에 담기',
  homeSaveCartButton: '카트 저장',
  homeCartTotalLabel: '현재 카트 합계',
  homeContinueScanAction: '계속 스캔하기',
  homeRecentSavedAction: '지난 카트 보기',
  homeExploreEntryTitle: '탐색에서 다음 판단 이어가기',
  homeExploreEntryBody: '비교 후보와 대안을 한 번에 보고 결정해보세요',
  savedSubtitle: '저장한 장보기 기록을 다시 확인해보세요',
  mySubtitle: '계정과 지난 카트를 한곳에서 관리해보세요',
  loginPageTitle: '로그인',
  loginSubtitle: '저장한 카트와 스캔 기록을 이어서 보시려면 로그인해 주세요',
  loginBenefitsTitle: '로그인하면 더 편해져요',
  loginBenefitsBody: '• 저장한 카트를 계속 보실 수 있어요\n• 다음 장보기 전에 다시 확인하실 수 있어요\n• 더 나은 대안을 비교해보실 수 있어요',
  loginModeLogin: '로그인',
  loginModeSignup: '회원가입',
  loginModeReset: '비밀번호 찾기',
  loginNameFieldLabel: '이름',
  loginEmailFieldLabel: '이메일',
  loginEmailLocalFieldLabel: '이메일 아이디',
  loginEmailDomainFieldLabel: '도메인',
  loginEmailCustomDomainOption: '직접입력',
  loginEmailCustomDomainFieldLabel: '직접 입력 도메인',
  loginPasswordFieldLabel: '비밀번호',
  loginPasswordConfirmFieldLabel: '비밀번호 확인',
  loginCodeFieldLabel: '인증 코드',
  loginForgotPasswordAction: '비밀번호를 잊으셨나요?',
  loginInvalidPasswordMessage: '비밀번호를 확인해 주세요',
  loginExistingEmailTitle: '이미 가입된 이메일입니다',
  loginExistingEmailBody: '이미 가입된 이메일입니다. 로그인하시거나 비밀번호를 재설정해 주세요.',
  loginExistingEmailLoginAction: '로그인하기',
  loginExistingEmailResetAction: '비밀번호 재설정',
  loginForgotPasswordPromptTitle: '비밀번호를 잊으셨나요?',
  loginForgotPasswordPromptBody: '비밀번호 입력을 여러 번 실패했습니다. 비밀번호 재설정으로 이동하시겠어요?',
  loginForgotPasswordPromptStay: '다시 입력하기',
  loginForgotPasswordPromptReset: '비밀번호 재설정',
  loginNewPasswordLabel: '새 비밀번호',
  loginSendingCode: '전송 중입니다...',
  loginResendCode: '재전송',
  loginSendCode: '코드 전송',
  loginSubmitting: '처리 중입니다...',
  loginSignupSubmit: '회원가입 완료',
  loginResetSubmit: '비밀번호 재설정',
  loginLoginSubmit: '로그인',
  loginContinueAsGuest: '게스트로 계속하기',
  loginSignupCodeSent: '이메일 인증 코드를 보내드렸습니다',
  loginSignupCodeVerified: '이메일 인증이 완료되었습니다',
  loginSignupVerifyCodeAction: '인증 코드 확인',
  loginSignupVerifyingCode: '인증 확인 중입니다...',
  loginSignupVerifiedBadge: '인증 완료',
  loginResetCodeSent: '비밀번호 재설정 코드를 보내드렸습니다',
  loginResetBackToLogin: '로그인으로 돌아가기',
  loginValidationEmailRequired: '이메일을 입력해 주세요',
  loginValidationEmailPasswordRequired: '이메일과 비밀번호를 입력해 주세요',
  loginValidationSignupFieldsRequired: '이름과 인증 코드를 모두 입력해 주세요',
  loginValidationNameRequired: '이름을 입력해 주세요',
  loginValidationSignupCodeVerifyRequired: '이메일 인증을 먼저 완료해 주세요',
  loginValidationPasswordTooShort: '비밀번호는 8자 이상이어야 합니다',
  loginValidationPasswordMismatch: '비밀번호 확인이 일치하지 않습니다',
  loginValidationCodeRequired: '인증 코드를 입력해 주세요',
  savedEmptyTitle: '아직 저장된 카트가 없어요',
  savedEmptyBody: '홈에서 카트를 저장하면 여기서 다시 볼 수 있어요.',
  recentSavedTitle: '최근 저장한 카트',
  recentSavedEmptyBody: '아직 저장한 카트가 없어요. 카트를 저장하면 다음 장보기 전에 다시 꺼내보실 수 있어요.',
  savedAdFallbackTitle: '함께 보면 좋은 혜택',
  savedAdFallbackMessage: '지난 카트를 다시 보는 흐름을 해치지 않는 선에서 꼭 맞는 혜택만 보여드릴게요.',
  savedAdSecondaryFallbackTitle: '비슷한 상품 혜택',
  savedAdSecondaryFallbackMessage: '기록을 보는 흐름은 그대로 두고, 필요한 혜택만 가볍게 보여드릴게요.',
  myBenefitsTitle: '계정을 연결하면 이런 점이 좋아요',
  myBenefitsBody: '• 지난 카트를 계속 보실 수 있어요\n• 최근 스캔 결과를 이어서 확인하실 수 있어요\n• 다음 장보기 전에 다시 비교하실 수 있어요',
  myMemberBody: '계정 정보와 지난 장보기 기록을 여기서 함께 관리하실 수 있어요.',
  myGuestModeLabel: '게스트로 사용 중이에요',
  myGuestSignupAction: '회원가입하기',
  myLoginAction: '로그인 / 회원가입',
  myLogoutAction: '로그아웃',
  myLinkedDoneMessage: '계정이 연결되었어요',
  myLogoutDoneMessage: '로그아웃되었어요',
  mySavedSectionTitle: '지난 카트',
  mySavedSectionMemberSubtitle: '저장해둔 지난 카트를 여기서 다시 확인해보세요',
  mySavedSectionGuestSubtitle: '게스트로 저장한 카트도 여기서 함께 확인하실 수 있어요',
  myAdFallbackTitle: '회원 전용 혜택 준비 중',
  myAdFallbackMessage: '마이에서는 계정과 잘 맞는 혜택만 보여드릴 예정이에요.',
  myComplianceTitle: '',
  myComplianceBody: '',
  myPrivacyPolicyLabel: '개인정보 처리방침',
  myPrivacyPolicyUrl: 'https://scan-api.seoa-nas.com/privacy',
  mySupportEmailLabel: '문의',
  mySupportEmail: 'scancart.wimc@gmail.com',
  mySupportPhoneLabel: '고객센터 연락처',
  mySupportPhone: '',
  mySupportHoursLabel: '응답 안내',
  mySupportHours: '',
  myBusinessInfoLabel: '운영 정보',
  myBusinessInfo: '',
  mySupportNote: '',
  drawerGuestTitle: '아직 로그인하지 않으셨어요',
  drawerGuestBody: '저장한 카트와 스캔 기록을 이어서 보시려면 로그인해 주세요.',
  saveCompleteTitle: '카트를 저장했어요',
  saveCompleteSubtitle: '다음 장보기 때 다시 꺼내보실 수 있어요',
  saveCompleteAdFallbackTitle: '더 나은 대안 보기',
  saveCompleteAdFallbackMessage: '결제 전에 가볍게 비교해보실 수 있는 선택지를 보여드릴게요.',
  saveCompleteViewSavedAction: '지난 카트 보기',
  commonCancel: '취소',
  commonConfirm: '확인',
  commonEdit: '수정',
  commonLoading: '불러오는 중...',
  cartDetailTitleSuffix: '카트',
  cartDetailEdit: '수정',
  cartDetailDone: '완료',
  cartDetailDeleteDialogTitle: '이 카트를 삭제할까요?',
  cartDetailDeleteDialogBody: '삭제하면 되돌릴 수 없어요.',
  cartDetailDeleteConfirm: '삭제',
  cartDetailDeleteCancel: '취소',
  cartDetailEmpty: '카트가 비었어요',
  cartDetailItemAdded: '상품을 추가했어요',
  cartDetailSavedSnapshotDone: '새 저장본으로 기록했어요',
  cartDetailNameLabel: '상품명',
  cartDetailPriceLabel: '가격',
  cartDetailApply: '적용',
  cartDetailTotalLabel: '총 합계',
  cartDetailSaveButton: '저장하기',
  cartDetailSaving: '저장 중…',
  cartDetailValidationNamePriceRequired: '상품명/가격을 확인해주세요',
  cartDetailValidationNameRequired: '상품명이 비어있어요',
  cartDetailValidationPriceQuantityRequired: '가격/수량을 확인해주세요',
  receiptCompareContextBody: '영수증과 저장한 카트를 나란히 확인해보세요.',
  receiptCompareEntryAction: '영수증 비교하기',
  receiptCompareSavedCartOnlyBadge: '저장 카트 전용',
  receiptReminderDelayMinutes: 60,
  publicSiteEyebrow: 'Cartly · private beta',
  publicSiteHeroTitle: '장보기를 기록하고, 같은 구매 의도 안에서 더 나은 선택을 찾는 앱',
  publicSiteHeroBody: 'Cartly는 스캔, 현재 카트, 저장된 장보기 기록을 바탕으로 사용자가 이미 사려던 상품과 같은 의도의 대체안을 다시 검토할 수 있게 도와줍니다.',
  publicSitePrimaryCtaLabel: '작동 방식 보기',
  publicSiteSecondaryCtaLabel: '개인정보 안내',
  publicSiteHeroPoints: '상품 스캔 및 검토\n현재 카트와 저장된 장보기 기록 관리\n같은 구매 의도(same-intent) 기준 대체안 탐색\n사용자 탭 이후에만 외부 파트너 링크 열기',
  publicSiteEnabledSections: 'hero,flow,status,partnerReview,linkPlacement',
  publicSiteSectionOrder: 'hero,flow,status,partnerReview,linkPlacement',
  publicSiteFlowTitle: '사용자 흐름',
  publicSiteFlowBody: '아래 흐름은 실제 앱에서 파트너 오퍼가 어떻게 맥락 안에서 노출되는지 설명하기 위한 개요입니다.',
  publicSiteStatusTitle: '현재 운영 상태',
  publicSiteStatusPoints: 'iOS private beta(TestFlight) 운영 중\nOCR 스캔, 카트 저장, 반복 구매 맥락 정리 기능 포함\nExplore 탭은 same-intent alternative 중심으로 고도화 중',
  publicSitePartnerReviewTitle: '파트너 검토 참고',
  publicSitePartnerReviewPoints: '무작위 광고 피드가 아니라 장보기 의사결정 보조 흐름 안에 배치됩니다.\n사용자 액션 없이 외부 링크를 자동 실행하지 않습니다.\n제품 맥락과 구매 의도를 유지하는 대체안만 다룹니다.',
  publicSiteLinkPlacementTitle: '파트너 링크가 붙는 위치',
  publicSiteLinkPlacementBody: 'Cartly는 무관한 크로스셀 피드 대신, 사용자가 이미 사려던 상품과 같은 구매 의도를 유지하는 대체안만 Explore 영역에서 보여주도록 설계되어 있습니다.',
  publicSiteLinkPlacementPoints: '최근 스캔 후 아직 확정하지 않은 상품\n현재 카트에 담긴 핵심 구매 후보\n반복 구매 가능성이 높은 저장 카트 품목',
  publicSitePrivacyTitle: '개인정보 및 외부 링크 안내',
  publicSitePrivacyIntro: 'Cartly는 사용자가 직접 추가하거나 스캔한 장보기 상품 정보와, 앱 실행 중 확인한 현재 위치 또는 대략적 지역 정보를 바탕으로 현재 카트, 저장된 장보기 기록, 근처 마트 할인정보 확인, 그리고 같은 구매 의도를 유지하는 대체안 탐색 흐름을 제공합니다.',
  publicSitePrivacyCollectionTitle: '수집 및 사용',
  publicSitePrivacyCollectionPoints: '상품명, 가격, 수량, 저장 카트 제목 등 장보기 기록\n스캔 기능 사용 시 업로드한 이미지와 인식 결과\n앱 실행 중 확인한 현재 위치 또는 대략적 지역 정보(근처 마트 할인정보 확인 목적)\n앱 기능 개선과 사용자 경험 향상을 위한 최소 운영 로그',
  publicSitePrivacyExternalTitle: '외부 링크',
  publicSitePrivacyExternalBody: '외부 쇼핑 링크는 사용자가 Explore 영역에서 특정 대체안을 선택했을 때만 열립니다. 자동 리디렉션이나 무관한 광고성 이동을 기본 동작으로 사용하지 않습니다.',
  publicSitePrivacyStatusTitle: '현재 상태',
  publicSitePrivacyStatusBody: 'Cartly는 현재 private beta 단계에서 제품 흐름을 다듬고 있습니다. 파트너 링크는 같은 구매 의도 안에서의 대체안 검토를 돕는 용도로만 사용됩니다.',
  publicSitePrivacyBackAction: '메인 페이지로 돌아가기',
  scanCaptureButton: '가격표 인식하기',
  scanUploadButton: '이미지 파일을 업로드 하세요',
  scanManualAddAction: '직접 추가하기',
  scanRecognizedTitle: '인식 결과',
  scanManualAddTitle: '직접 추가하기',
  scanUploading: '업로드 중...',
  scanQueued: '대기 중...',
  scanProcessing: '분석 중...',
  scanResultPreparing: '결과 정리 중...',
  scanFailed: '인식에 실패했어요',
  scanTimeout: '분석이 조금 지연되고 있어요. 잠시 후 다시 시도해봐요',
  scanResultEmpty: '텍스트를 못 읽었어요. 더 가까이/선명하게 찍어봐요',
  scanProcessingError: '분석 처리 중 오류가 났어요',
  scanRetakeAction: '다시 찍기',
  scanRecognizeAction: '인식',
  scanRecognizing: '인식 중...',
}

export const mockExploreSettings = {
  enabledSections: 'heroSummary,decisionInbox,revisitItems,repeatCandidates,editorialPicks,offerSlots,savedContext,storeContextPromo',
  sectionOrder: 'heroSummary,decisionInbox,revisitItems,repeatCandidates,editorialPicks,offerSlots,savedContext,storeContextPromo',
  stateMode: 'auto',
  activeShoppingSectionOrder: 'offerSlots,heroSummary,decisionInbox,revisitItems',
  postSaveSectionOrder: 'savedContext,decisionInbox,repeatCandidates,editorialPicks,offerSlots',
  idlePlanningSectionOrder: 'savedContext,repeatCandidates,editorialPicks,offerSlots',
  storeContextSectionOrder: 'storeContextPromo,savedContext,editorialPicks,repeatCandidates,offerSlots',
  stateRules: {
    activeShopping: {
      revisitRecentScanLimit: 3,
      revisitCartItemLimit: 3,
      revisitMaxItems: 4,
      repeatMinCount: 2,
      repeatMaxItems: 2,
      offerMaxSlots: 3,
      storeContextMaxPromos: 0,
    },
    postSave: {
      revisitRecentScanLimit: 2,
      revisitCartItemLimit: 2,
      revisitMaxItems: 3,
      repeatMinCount: 2,
      repeatMaxItems: 4,
      offerMaxSlots: 3,
      storeContextMaxPromos: 1,
    },
    idlePlanning: {
      revisitRecentScanLimit: 0,
      revisitCartItemLimit: 0,
      revisitMaxItems: 0,
      repeatMinCount: 2,
      repeatMaxItems: 4,
      offerMaxSlots: 2,
      storeContextMaxPromos: 0,
    },
    storeContext: {
      revisitRecentScanLimit: 0,
      revisitCartItemLimit: 0,
      revisitMaxItems: 0,
      repeatMinCount: 2,
      repeatMaxItems: 3,
      offerMaxSlots: 2,
      storeContextMaxPromos: 3,
    },
  },
  statePromoPolicies: {
    activeShopping: {
      allowSponsoredPromos: false,
      maxSponsoredPromos: 0,
      organicFirst: true,
    },
    postSave: {
      allowSponsoredPromos: true,
      maxSponsoredPromos: 1,
      organicFirst: true,
    },
    idlePlanning: {
      allowSponsoredPromos: true,
      maxSponsoredPromos: 1,
      organicFirst: true,
    },
    storeContext: {
      allowSponsoredPromos: true,
      maxSponsoredPromos: 2,
      organicFirst: false,
    },
  },
  decisionCopy: {
    recentScanPendingReasonLabel: '아직 담기 전이에요',
    recentScanPendingBody: '방금 스캔했지만 아직 카트에 담지 않았어요. 지금 확인해 두시면 놓치지 않아요.',
    recentScanInCartReasonLabel: '담은 뒤 한 번 더 보기',
    recentScanInCartBody: '이미 카트에 담았어요. 결제 전에 다른 선택지가 있는지만 가볍게 확인해보세요.',
    currentCartHighImpactReasonLabel: '합계 영향이 커요',
    currentCartHighImpactBody: '수량이나 가격 영향이 큰 상품이에요. 비슷한 대안과 비교하면 체감 차이가 날 수 있어요.',
    currentCartDefaultReasonLabel: '결제 전에 확인해보세요',
    currentCartDefaultBody: '지금 카트에 담아둔 상품이에요. 결제 전에 한 번만 더 비교해보세요.',
    offerReasonLabelActiveShopping: '지금 비교해보세요',
    offerReasonLabelPostSave: '저장한 뒤 다시 보기',
    offerReasonLabelIdlePlanning: '다음 장보기 준비',
    offerReasonLabelStoreContext: '지금 매장 할인 보기',
    offerBody: '같은 용도의 다른 선택지를 바로 비교하실 수 있어요. 가격이나 구성만 가볍게 확인해보세요.',
  },
  stateDecisionPriorities: {
    activeShopping: {
      offerPendingReview: 300,
      offerCurrentCart: 280,
      offerRepeatPurchase: 180,
      currentCartHighImpact: 240,
      recentScanPending: 220,
      recentScanInCart: 180,
      currentCartDefault: 160,
    },
    postSave: {
      offerPendingReview: 220,
      offerCurrentCart: 250,
      offerRepeatPurchase: 280,
      recentScanInCart: 240,
      currentCartDefault: 210,
      currentCartHighImpact: 180,
      recentScanPending: 160,
    },
    idlePlanning: {
      offerPendingReview: 150,
      offerCurrentCart: 140,
      offerRepeatPurchase: 220,
      recentScanPending: 210,
      currentCartDefault: 180,
      recentScanInCart: 150,
      currentCartHighImpact: 140,
    },
    storeContext: {
      offerPendingReview: 300,
      offerCurrentCart: 320,
      offerRepeatPurchase: 200,
      currentCartHighImpact: 230,
      recentScanInCart: 210,
      currentCartDefault: 180,
      recentScanPending: 150,
    },
  },
  stateDecisionMaxCounts: {
    activeShopping: {
      offerPendingReview: 1,
      offerCurrentCart: 1,
      offerRepeatPurchase: 1,
      recentScanPending: 1,
      recentScanInCart: 1,
      currentCartHighImpact: 1,
      currentCartDefault: 1,
    },
    postSave: {
      offerPendingReview: 1,
      offerCurrentCart: 1,
      offerRepeatPurchase: 2,
      recentScanPending: 1,
      recentScanInCart: 2,
      currentCartHighImpact: 1,
      currentCartDefault: 2,
    },
    idlePlanning: {
      offerPendingReview: 1,
      offerCurrentCart: 1,
      offerRepeatPurchase: 2,
      recentScanPending: 2,
      recentScanInCart: 1,
      currentCartHighImpact: 1,
      currentCartDefault: 1,
    },
    storeContext: {
      offerPendingReview: 1,
      offerCurrentCart: 2,
      offerRepeatPurchase: 1,
      recentScanPending: 1,
      recentScanInCart: 1,
      currentCartHighImpact: 1,
      currentCartDefault: 1,
    },
  },
  revisitRecentScanLimit: 3,
  revisitCartItemLimit: 3,
  revisitMaxItems: 4,
  repeatMinCount: 2,
  repeatMaxItems: 4,
  offerMaxSlots: 3,
  editorialRecommendationsEnabled: true,
  editorialRecommendationsTitle: '추천 제품',
  editorialRecommendationsSubtitle: '지금 카트에 많이 담는 TOP5',
  editorialRecommendationsCount: 5,
  editorialRecommendationsPoolRaw: [
    '삼다수 2L 12개 | 12900 | https://placehold.co/160x160/png?text=Water | https://link.coupang.com/example-water',
    '비비고 왕교자 | 8990 | https://placehold.co/160x160/png?text=Dumpling | https://link.coupang.com/example-dumpling',
    '켈로그 콘푸로스트 | 7480 | https://placehold.co/160x160/png?text=Cereal | https://link.coupang.com/example-cereal',
    '서울우유 1L 2입 | 5980 | https://placehold.co/160x160/png?text=Milk | https://link.coupang.com/example-milk',
    '코카콜라 제로 24캔 | 18900 | https://placehold.co/160x160/png?text=Cola | https://link.coupang.com/example-cola',
    '동원 참치 8캔 | 13980 | https://placehold.co/160x160/png?text=Tuna | https://link.coupang.com/example-tuna',
  ].join('\n'),
  editorialRecommendationsDisclaimer:
    '이 섹션에는 제휴 링크가 포함될 수 있으며, 이에 따라 일정 수수료를 제공받을 수 있어요.',
  editorialRecommendationsItems: [
    {
      id: 'editorial-pick-1',
      title: '삼다수 2L 12개',
      price: 12900,
      thumbnailUrl: 'https://placehold.co/160x160/png?text=Water',
      url: 'https://link.coupang.com/example-water',
      deeplinkUrl: 'https://link.coupang.com/example-water',
      provider: '쿠팡 추천',
    },
    {
      id: 'editorial-pick-2',
      title: '비비고 왕교자',
      price: 8990,
      thumbnailUrl: 'https://placehold.co/160x160/png?text=Dumpling',
      url: 'https://link.coupang.com/example-dumpling',
      deeplinkUrl: 'https://link.coupang.com/example-dumpling',
      provider: '쿠팡 추천',
    },
    {
      id: 'editorial-pick-3',
      title: '켈로그 콘푸로스트',
      price: 7480,
      thumbnailUrl: 'https://placehold.co/160x160/png?text=Cereal',
      url: 'https://link.coupang.com/example-cereal',
      deeplinkUrl: 'https://link.coupang.com/example-cereal',
      provider: '쿠팡 추천',
    },
    {
      id: 'editorial-pick-4',
      title: '서울우유 1L 2입',
      price: 5980,
      thumbnailUrl: 'https://placehold.co/160x160/png?text=Milk',
      url: 'https://link.coupang.com/example-milk',
      deeplinkUrl: 'https://link.coupang.com/example-milk',
      provider: '쿠팡 추천',
    },
    {
      id: 'editorial-pick-5',
      title: '코카콜라 제로 24캔',
      price: 18900,
      thumbnailUrl: 'https://placehold.co/160x160/png?text=Cola',
      url: 'https://link.coupang.com/example-cola',
      deeplinkUrl: 'https://link.coupang.com/example-cola',
      provider: '쿠팡 추천',
    },
    {
      id: 'editorial-pick-6',
      title: '동원 참치 8캔',
      price: 13980,
      thumbnailUrl: 'https://placehold.co/160x160/png?text=Tuna',
      url: 'https://link.coupang.com/example-tuna',
      deeplinkUrl: 'https://link.coupang.com/example-tuna',
      provider: '쿠팡 추천',
    },
  ],
  storeContextEnabled: false,
  storeContextStoreName: '이마트 양재점',
  storeContextPromoTitle: '지금 이 마트 세일',
  storeContextPromoBody: '자주 사는 상품군과 겹치는 할인 행사부터 먼저 보여줘요.',
  storeContextPromoCtaLabel: '행사 보기',
  storeContextPromoSeedLabels: '유제품 세일,음료 행사,오늘의 마트 추천',
  storeContextPromoSourceType: 'storeSale',
  storeContextPromoSponsored: false,
  storeContextPromoSponsorLabel: '',
  storeContextPromoPriorityStart: 100,
  storeContextMaxPromos: 3,
  storeContextPromos: [
    {
      id: 'store-promo-1',
      title: '유제품 세일 확인',
      body: '자주 사는 상품군과 겹치는 할인 행사부터 먼저 보여줘요.',
      badgeLabel: '유제품 세일',
      storeName: '이마트 양재점',
      ctaLabel: '행사 보기',
      placementLabel: '매장 프로모션',
      intentHint: '같은 구매 의도 기준',
      source: 'store-context-preview',
      sourceType: 'storeSale',
      priority: 100,
      isSponsored: false,
      sponsorLabel: '',
    },
    {
      id: 'store-promo-2',
      title: '음료 행사 확인',
      body: '자주 사는 상품군과 겹치는 할인 행사부터 먼저 보여줘요.',
      badgeLabel: '음료 행사',
      storeName: '이마트 양재점',
      ctaLabel: '행사 보기',
      placementLabel: '매장 프로모션',
      intentHint: '같은 구매 의도 기준',
      source: 'store-context-preview',
      sourceType: 'storeSale',
      priority: 90,
      isSponsored: false,
      sponsorLabel: '',
    },
    {
      id: 'store-promo-3',
      title: '오늘의 마트 추천 확인',
      body: '자주 사는 상품군과 겹치는 할인 행사부터 먼저 보여줘요.',
      badgeLabel: '오늘의 마트 추천',
      storeName: '이마트 양재점',
      ctaLabel: '행사 보기',
      placementLabel: '매장 프로모션',
      intentHint: '같은 구매 의도 기준',
      source: 'store-context-preview',
      sourceType: 'storeSale',
      priority: 80,
      isSponsored: false,
      sponsorLabel: '',
    },
  ],
}

export const mockPushAdmin = {
  status: {
    enabled: true,
    provider: 'fcm',
    ready: true,
    blockers: [],
    firebaseProjectId: 'cartly-e36ee',
    devices: {
      total: 3,
      active: 3,
      tokenReady: 2,
    },
  },
  devices: [
    {
      id: 'push_device_1',
      userId: 'usr_002',
      installId: 'ios-install-1',
      platform: 'ios',
      pushProvider: 'fcm',
      hasPushToken: true,
      notificationsEnabled: true,
      status: 'active',
      appVersion: '1.0.3+50',
      locale: 'ko-KR',
      lastRegisteredAt: MOCK_TIMESTAMP,
      lastSeenAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'push_device_2',
      userId: null,
      installId: 'android-install-2',
      platform: 'android',
      pushProvider: 'fcm',
      hasPushToken: true,
      notificationsEnabled: true,
      status: 'active',
      appVersion: '1.0.3+50',
      locale: 'ko-KR',
      lastRegisteredAt: MOCK_TIMESTAMP,
      lastSeenAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
  ],
  campaigns: [
    {
      id: 'push_campaign_1',
      kind: 'notice',
      audience: 'all',
      status: 'sent',
      title: '오늘 운영 공지',
      message: '지금은 장보기 저장과 영수증 등록 흐름을 점검하고 있어요.',
      targetTab: 'home',
      targetUrl: null,
      requestedBy: 'sd467589',
      requestedBySource: 'root_token',
      deliveryProvider: 'fcm',
      errorMessage: null,
      createdAt: MOCK_TIMESTAMP,
      sentAt: MOCK_TIMESTAMP,
    },
    {
      id: 'push_campaign_2',
      kind: 'promotion',
      audience: 'members',
      status: 'no_targets',
      title: '혜택 알림 테스트',
      message: '실제 토큰이 아직 없는 기기에는 보내지지 않아요.',
      targetTab: 'explore',
      targetUrl: null,
      requestedBy: 'sd467589',
      requestedBySource: 'root_token',
      deliveryProvider: 'fcm',
      errorMessage: 'No eligible push tokens registered',
      createdAt: MOCK_TIMESTAMP,
      sentAt: null,
    },
  ],
}

export const mockConfig = {
  remoteScan: true,
  adsEnabled: true,
  serviceName: 'Cartly API',
  storageRoot: '/Volumes/AI/Cartly',
  storageRootDisplay: '/Volumes/AI/Cartly',
  storageRootActual: '/Volumes/AI/Cartly',
  storageWritable: true,
  storagePaths: {
    root: '/Volumes/AI/Cartly',
    input: '/Volumes/AI/Cartly/input/2026-03-24',
    feedbackLogs: '/Volumes/AI/Cartly/logs/feedback/2026-03-24',
    failureLogs: '/Volumes/AI/Cartly/logs/failures/2026-03-24',
    failed: '/Volumes/AI/Cartly/failed/2026-03-24',
  },
  storageErrors: [],
  backendRunMode: 'terminal-login-session-supervised',
  runtimeAssetsRoot: '~/Library/Application Support/Cartly/assets',
  runtimeAssetsRootDisplay: '~/Library/Application Support/Cartly/assets',
  runtimeAssetsRootActual: '~/Library/Application Support/Cartly/assets',
  brandingAssetsDir: '~/Library/Application Support/Cartly/assets/branding',
  brandingAssetsDirDisplay: '~/Library/Application Support/Cartly/assets/branding',
  brandingAssetsDirActual: '~/Library/Application Support/Cartly/assets/branding',
  adsAssetsDir: '~/Library/Application Support/Cartly/assets/ads',
  adsAssetsDirDisplay: '~/Library/Application Support/Cartly/assets/ads',
  adsAssetsDirActual: '~/Library/Application Support/Cartly/assets/ads',
  legacyPathCompatibilityActive: true,
  apiBase: 'http://127.0.0.1:8011',
  branding: mockBranding,
  publicSite: {
    dynamicLandingEnabled: true,
    landingRoutes: ['/', '/partners'],
    privacyRoutes: ['/privacy'],
    assetsRoutePrefix: '/assets/branding',
  },
  runtimeSettings: {
    receiptReminderDelayMinutes: 60,
    myPageInsightsEnabled: true,
    myPageSummaryMonths: 3,
    myPageTopCategoriesCount: 3,
    myPageTopItemsCount: 3,
    myPageSectionOrder: ['recentSaved', 'monthlySummary', 'allSavedHistory'],
    myPageCategoryGroups: [
      { id: 'food', label: '식품', keywords: ['우유', '계란', '바나나', '사과', '샐러드'] },
      { id: 'life_health', label: '생활/건강', keywords: ['휴지', '세제', '샴푸', '비누', '영양제'] },
      { id: 'digital', label: '디지털/가전', keywords: ['이어폰', '충전기', '가전', '청소기'] },
      { id: 'fashion_clothes', label: '패션의류', keywords: ['티셔츠', '바지', '원피스', '양말'] },
      { id: 'fashion_goods', label: '패션잡화', keywords: ['운동화', '가방', '모자', '지갑'] },
      { id: 'beauty', label: '화장품/미용', keywords: ['토너', '로션', '크림', '클렌징'] },
      { id: 'furniture', label: '가구/인테리어', keywords: ['의자', '책상', '조명', '침구'] },
      { id: 'baby', label: '출산/육아', keywords: ['기저귀', '분유', '물티슈', '이유식'] },
      { id: 'sports', label: '스포츠/레저', keywords: ['덤벨', '캠핑', '자전거', '러닝'] },
      { id: 'leisure', label: '여가/생활편의', keywords: ['티켓', '도서', '문구', '반려동물'] },
    ],
  },
  coupangPartners: {
    enabled: false,
    envEnabled: false,
    enabledOverride: null,
    configSource: 'env_default',
    accessKeyConfigured: false,
    secretKeyConfigured: false,
    affiliateReady: false,
    operatorNote: '쿠팡 답변 전까지 기본 OFF 유지',
    recentChanges: [
      {
        changedAt: MOCK_TIMESTAMP,
        configSource: 'env_default',
        enabledOverride: null,
        effectiveEnabled: false,
        operatorNote: '쿠팡 답변 전까지 기본 OFF 유지',
      },
    ],
    updatedAt: MOCK_TIMESTAMP,
  },
  smoke: {
    checkedAt: MOCK_TIMESTAMP,
    ok: true,
    results: [
      { key: 'localBackendHealth', label: 'Local backend /health', url: 'http://127.0.0.1:8011/health', status: 200, ok: true, durationMs: 42 },
      { key: 'publicApiHealth', label: 'Public API /health', url: `${CARTLY_PUBLIC_APP_BASE_URL}/health`, status: 200, ok: true, durationMs: 96 },
      { key: 'publicLanding', label: 'Public landing /', url: `${CARTLY_PUBLIC_APP_BASE_URL}/`, status: 200, ok: true, durationMs: 103 },
      { key: 'publicPrivacy', label: 'Public privacy /privacy', url: `${CARTLY_PUBLIC_APP_BASE_URL}/privacy`, status: 200, ok: true, durationMs: 101 },
      { key: 'publicAppConfig', label: 'Public app-config /v1/app-config', url: `${CARTLY_PUBLIC_APP_BASE_URL}/v1/app-config`, status: 200, ok: true, durationMs: 108 },
      { key: 'adminLogin', label: 'Admin login /login', url: `${CARTLY_PUBLIC_ADMIN_BASE_URL}/login`, status: 200, ok: true, durationMs: 94 },
    ],
    history: [
      {
        checkedAt: MOCK_TIMESTAMP,
        ok: true,
        failureCount: 0,
        results: [
          { key: 'localBackendHealth', label: 'Local backend /health', url: 'http://127.0.0.1:8011/health', status: 200, ok: true, durationMs: 42 },
          { key: 'publicApiHealth', label: 'Public API /health', url: `${CARTLY_PUBLIC_APP_BASE_URL}/health`, status: 200, ok: true, durationMs: 96 },
          { key: 'publicLanding', label: 'Public landing /', url: `${CARTLY_PUBLIC_APP_BASE_URL}/`, status: 200, ok: true, durationMs: 103 },
          { key: 'publicPrivacy', label: 'Public privacy /privacy', url: `${CARTLY_PUBLIC_APP_BASE_URL}/privacy`, status: 200, ok: true, durationMs: 101 },
          { key: 'publicAppConfig', label: 'Public app-config /v1/app-config', url: `${CARTLY_PUBLIC_APP_BASE_URL}/v1/app-config`, status: 200, ok: true, durationMs: 108 },
          { key: 'adminLogin', label: 'Admin login /login', url: `${CARTLY_PUBLIC_ADMIN_BASE_URL}/login`, status: 200, ok: true, durationMs: 94 },
        ],
      },
    ],
  },
  smokeHistory: [
    {
      checkedAt: MOCK_TIMESTAMP,
      ok: true,
      failureCount: 0,
      results: [
        { key: 'localBackendHealth', label: 'Local backend /health', url: 'http://127.0.0.1:8011/health', status: 200, ok: true, durationMs: 42 },
        { key: 'publicApiHealth', label: 'Public API /health', url: `${CARTLY_PUBLIC_APP_BASE_URL}/health`, status: 200, ok: true, durationMs: 96 },
        { key: 'publicLanding', label: 'Public landing /', url: `${CARTLY_PUBLIC_APP_BASE_URL}/`, status: 200, ok: true, durationMs: 103 },
        { key: 'publicPrivacy', label: 'Public privacy /privacy', url: `${CARTLY_PUBLIC_APP_BASE_URL}/privacy`, status: 200, ok: true, durationMs: 101 },
        { key: 'publicAppConfig', label: 'Public app-config /v1/app-config', url: `${CARTLY_PUBLIC_APP_BASE_URL}/v1/app-config`, status: 200, ok: true, durationMs: 108 },
        { key: 'adminLogin', label: 'Admin login /login', url: `${CARTLY_PUBLIC_ADMIN_BASE_URL}/login`, status: 200, ok: true, durationMs: 94 },
      ],
    },
  ],
}
