const MOCK_TIMESTAMP = '2026-03-23T00:00:00.000Z'

export const mockSummary = {
  dau: 128,
  wau: 602,
  mau: 1820,
  comparisons: {
    dau: { day: 120, week: 116, month: 109 },
    wau: { day: 590, week: 564, month: 521 },
    mau: { day: 1792, week: 1748, month: 1684 },
  },
  activeUsers: 941,
  newUsers: 214,
  guestToMemberConversion: 0.124,
  totalScans: 4821,
  scanSuccessRate: 0.71,
  cartSaveRate: 0.43,
  adImpressions: 1320,
  adClicks: 48,
  adCtr: 0.036,
  snapshotDate: '2026-03-23',
  snapshotGeneratedAt: '2026-03-23T00:00:00.000Z',
  snapshotSource: 'scheduled',
  dataMode: 'snapshot',
  lifecycle: {
    guestProfiles: 420,
    trackedGuests: 188,
    legacyGuests: 12,
    legacyGuestsWithCarts: 3,
    activeMembers: 154,
    memberUsersWithSavedCarts: 91,
    memberSavedCarts: 268,
    avgSavedCartsPerMember: 2.95,
    guestToMemberConversions: 96,
    guestToMemberConversionRate: 0.229,
    topMembers: [
      {
        userId: 'usr_002',
        displayName: 'Seungdae',
        email: 'ceo@wimc.app',
        cartCount: 12,
        totalValue: 482000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
      {
        userId: 'usr_010',
        displayName: 'Power saver',
        email: 'member10@wimc.app',
        cartCount: 9,
        totalValue: 231000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
    ],
  },
}

export const mockPeriodSummary = {
  period: 'month',
  rangeStart: '2026-03-01',
  rangeEnd: '2026-03-23',
  activeUsers: 941,
  newUsers: 214,
  guestUsers: 160,
  memberUsers: 54,
  guestToMemberConversion: 0.252,
  totalScans: 4821,
  successfulScans: 3423,
  scanSuccessRate: 0.71,
  cartSaves: 2073,
  cartSaveRate: 0.43,
  adImpressions: 1320,
  adClicks: 48,
  adCtr: 0.036,
  adSlots: [
    { slotKey: 'save_complete_sheet_1', impressions: 420, clicks: 16, ctr: 0.0381 },
    { slotKey: 'saved_inline_1', impressions: 360, clicks: 14, ctr: 0.0389 },
    { slotKey: 'saved_inline_2', impressions: 280, clicks: 9, ctr: 0.0321 },
    { slotKey: 'my_perks_inline_1', impressions: 260, clicks: 9, ctr: 0.0346 },
  ],
  deviceBreakdownReady: true,
  lifecycle: {
    guestProfiles: 88,
    trackedGuests: 74,
    legacyGuests: 14,
    legacyGuestsWithCarts: 2,
    activeMembers: 54,
    memberUsersWithSavedCarts: 31,
    memberSavedCarts: 96,
    avgSavedCartsPerMember: 3.1,
    guestToMemberConversions: 19,
    guestToMemberConversionRate: 0.216,
    topMembers: [
      {
        userId: 'usr_002',
        displayName: 'Seungdae',
        email: 'ceo@wimc.app',
        cartCount: 4,
        totalValue: 122000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
      {
        userId: 'usr_010',
        displayName: 'Power saver',
        email: 'member10@wimc.app',
        cartCount: 3,
        totalValue: 88000,
        lastSavedAt: MOCK_TIMESTAMP,
      },
    ],
  },
}

export const mockUsers = [
  {
    id: 'usr_001',
    displayName: 'Guest shopper',
    email: null,
    provider: 'guest',
    isGuest: true,
    guestKey: 'guest-ios-install-001',
    lastDevicePlatform: 'ios',
    lastAppVersion: '0.1.0',
    createdAt: MOCK_TIMESTAMP,
    lastSeenAt: MOCK_TIMESTAMP,
  },
  {
    id: 'usr_002',
    displayName: 'Seungdae',
    email: 'ceo@wimc.app',
    provider: 'google',
    isGuest: false,
    guestKey: null,
    lastDevicePlatform: 'ios',
    lastAppVersion: '0.1.0',
    createdAt: MOCK_TIMESTAMP,
    lastSeenAt: MOCK_TIMESTAMP,
  },
]

export const mockScanJobs = {
  summary: {
    jobsTotal: 2,
    feedbackTotal: 6,
    feedbackAccepted: 4,
    feedbackCorrected: 2,
    failureLogs: 3,
  },
  jobs: [
    {
      id: 'job_001',
      userId: 'usr_002',
      status: 'done',
      errorCode: null,
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
    {
      id: 'job_002',
      userId: null,
      status: 'failed',
      errorCode: 'OCR_NOT_CONFIDENT',
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
    },
  ],
  recentFeedback: [
    {
      id: 'fb_001',
      jobId: 'job_001',
      userId: 'usr_002',
      accepted: true,
      createdAt: MOCK_TIMESTAMP,
    },
    {
      id: 'fb_002',
      jobId: 'job_003',
      userId: 'usr_001',
      accepted: false,
      createdAt: MOCK_TIMESTAMP,
    },
  ],
  recentFailures: [
    {
      id: 'fail_001',
      jobId: 'job_002',
      userId: null,
      stage: 'processing',
      errorCode: 'OCR_NOT_CONFIDENT',
      errorMessage: '텍스트를 충분히 읽지 못했어',
      createdAt: MOCK_TIMESTAMP,
    },
  ],
}

export const mockCarts = {
  summary: {
    totalCarts: 12,
    memberCarts: 7,
    guestCarts: 3,
    anonymousCarts: 2,
    avgCartValue: 42800,
    avgItemCount: 4.2,
  },
  carts: [
    {
      id: 'cart_001',
      userId: 'usr_002',
      sourceCartId: null,
      title: '코스트코 주말 장보기',
      status: 'saved',
      savedDate: '2026-03-23',
      totalPrice: 68400,
      totalCount: 5,
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
      user: {
        id: 'usr_002',
        displayName: 'Seungdae',
        email: 'ceo@wimc.app',
        isGuest: false,
        provider: 'google',
      },
      items: [
        { id: 'item_001', name: '계란 30구', price: 8900, quantity: 1, source: 'manual', scanResultId: null },
        { id: 'item_002', name: '닭가슴살', price: 14900, quantity: 2, source: 'scan', scanResultId: 'job_001' },
      ],
    },
    {
      id: 'cart_002',
      userId: 'usr_001',
      sourceCartId: 'cart_001',
      title: null,
      status: 'saved',
      savedDate: '2026-03-24',
      totalPrice: 21900,
      totalCount: 2,
      createdAt: MOCK_TIMESTAMP,
      updatedAt: MOCK_TIMESTAMP,
      user: {
        id: 'usr_001',
        displayName: 'Guest shopper',
        email: null,
        isGuest: true,
        provider: 'guest',
      },
      items: [
        { id: 'item_003', name: '우유', price: 4900, quantity: 1, source: 'manual', scanResultId: null },
        { id: 'item_004', name: '시리얼', price: 17000, quantity: 1, source: 'manual', scanResultId: null },
      ],
    },
  ],
}

export const mockSlots = [
  {
    id: 'slot_001',
    slotKey: 'save_complete_sheet_1',
    placementType: 'bottom_sheet',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 88,
      screen: 'save_complete',
      position: 'after_summary_before_actions',
      tone: 'benefit_native',
      title: '다음 장보기도 더 가볍게',
      message: '저장한 카트를 기준으로 혜택 상품을 이어서 볼 수 있어요.',
      ctaLabel: '혜택 보기',
      targetUrl: null,
      imageUrl: null,
    },
  },
  {
    id: 'slot_002',
    slotKey: 'saved_inline_1',
    placementType: 'inline',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 104,
      screen: 'saved_list',
      position: 'after_first_card',
      tone: 'benefit_native',
      title: '지금 많이 담는 상품',
      message: 'Saved 카트와 같이 보는 추천 배너 슬롯이야.',
      ctaLabel: '자세히',
      targetUrl: null,
      imageUrl: null,
    },
  },
  {
    id: 'slot_003',
    slotKey: 'saved_inline_2',
    placementType: 'inline',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 104,
      screen: 'saved_list',
      position: 'after_third_card',
      tone: 'benefit_native',
      title: '같이 담기 좋은 상품',
      message: 'Saved 리스트 중간 보조 프로모션 슬롯이야.',
      ctaLabel: '확인',
      targetUrl: null,
      imageUrl: null,
    },
  },
  {
    id: 'slot_004',
    slotKey: 'my_perks_inline_1',
    placementType: 'inline',
    status: 'active',
    createdAt: MOCK_TIMESTAMP,
    updatedAt: MOCK_TIMESTAMP,
    config: {
      maxHeight: 96,
      screen: 'my',
      position: 'below_account_card',
      tone: 'soft_promo',
      title: '멤버 혜택 확인',
      message: 'My 화면용 보조 배너 슬롯이야.',
      ctaLabel: '보기',
      targetUrl: null,
      imageUrl: null,
    },
  },
]

export const mockBranding = {
  logoType: 'text',
  logoText: 'Cartly',
  logoImageUrl: null,
  splashImageUrl: null,
  loginHeroImageUrl: null,
  homeTabLabel: 'Home',
  helpTabLabel: '도움',
  myTabLabel: 'My',
}

export const mockContentSettings = {
  logoType: 'text',
  logoText: 'Cartly',
  logoImageUrl: null,
  splashImageUrl: null,
  loginHeroImageUrl: null,
  homeTabLabel: 'Home',
  helpTabLabel: '도움',
  myTabLabel: 'My',
  homePageTitle: 'Cartly',
  helpPageTitle: 'Shopping help',
  savedPageTitle: 'Saved carts',
  myPageTitle: 'My account',
  homeSubtitle: '지금 카트 총액을 확인해',
  helpSubtitle: '운영 부담이 큰 피드형 쇼핑 탭 대신, 정말 도움이 되는 기능부터 붙일 예정이야',
  homeRecentScanTitle: '최근 스캔',
  homeRecentScanSubtitle: '방금 읽은 결과',
  homeAddSectionTitle: '새 상품 추가',
  homeAddSectionSubtitle: '스캔하거나 바로 담기',
  homeCurrentCartTitle: '현재 카트',
  homeCurrentCartSubtitle: '결제 전 합계를 확인해',
  homeCurrentCartEmpty: '아직 담은 상품이 없어요',
  homeAddToCurrentCartDone: '현재 카트에 담았어요',
  homeAddToCurrentCartButton: '현재 카트에 담기',
  homeSaveCartButton: '카트 저장',
  homeCartTotalLabel: '현재 카트 합계',
  homeContinueScanAction: '계속 스캔하기',
  homeRecentSavedAction: '지난 카트 보기',
  savedSubtitle: '저장한 카트를 다시 봐',
  mySubtitle: '기록을 남기려면 로그인',
  loginPageTitle: '계정 시작',
  loginSubtitle: '저장과 기록을 이어가려면 로그인',
  loginBenefitsTitle: '왜 계정을 만들까요',
  loginBenefitsBody: '• 저장한 카트를 볼 수 있습니다\n• 다음 결제 전에 다시 확인할 수 있습니다\n• 더 저렴한 대안을 추천받을 수 있습니다',
  loginModeLogin: '로그인',
  loginModeSignup: '회원가입',
  loginModeReset: '비밀번호 찾기',
  loginNameFieldLabel: '이름',
  loginEmailFieldLabel: '이메일',
  loginEmailLocalFieldLabel: '이메일 아이디',
  loginEmailDomainFieldLabel: '도메인',
  loginEmailCustomDomainOption: '직접입력',
  loginEmailCustomDomainFieldLabel: '직접 입력 도메인',
  loginPasswordFieldLabel: '비밀번호',
  loginPasswordConfirmFieldLabel: '비밀번호 확인',
  loginCodeFieldLabel: '인증 코드',
  loginForgotPasswordAction: '비밀번호를 잊으셨나요?',
  loginInvalidPasswordMessage: '비밀번호를 확인해 주세요',
  loginExistingEmailTitle: '이미 가입된 이메일입니다',
  loginExistingEmailBody: '이미 가입된 이메일입니다. 로그인하시거나 비밀번호를 재설정해 주세요.',
  loginExistingEmailLoginAction: '로그인하기',
  loginExistingEmailResetAction: '비밀번호 재설정',
  loginForgotPasswordPromptTitle: '비밀번호를 잊으셨나요?',
  loginForgotPasswordPromptBody: '비밀번호 입력을 여러 번 실패했습니다. 비밀번호 재설정으로 이동하시겠어요?',
  loginForgotPasswordPromptStay: '다시 입력하기',
  loginForgotPasswordPromptReset: '비밀번호 재설정',
  loginNewPasswordLabel: '새 비밀번호',
  loginSendingCode: '전송 중입니다...',
  loginResendCode: '재전송',
  loginSendCode: '코드 전송',
  loginSubmitting: '처리 중입니다...',
  loginSignupSubmit: '회원가입 완료',
  loginResetSubmit: '비밀번호 재설정',
  loginLoginSubmit: '로그인',
  loginContinueAsGuest: '게스트로 계속하기',
  loginSignupCodeSent: '이메일 인증 코드를 보내드렸습니다',
  loginSignupCodeVerified: '이메일 인증이 완료되었습니다',
  loginSignupVerifyCodeAction: '인증 코드 확인',
  loginSignupVerifyingCode: '인증 확인 중입니다...',
  loginSignupVerifiedBadge: '인증 완료',
  loginResetCodeSent: '비밀번호 재설정 코드를 보내드렸습니다',
  loginResetBackToLogin: '로그인으로 돌아가기',
  loginValidationEmailRequired: '이메일을 입력해 주세요',
  loginValidationEmailPasswordRequired: '이메일과 비밀번호를 입력해 주세요',
  loginValidationSignupFieldsRequired: '이름과 인증 코드를 모두 입력해 주세요',
  loginValidationNameRequired: '이름을 입력해 주세요',
  loginValidationSignupCodeVerifyRequired: '이메일 인증을 먼저 완료해 주세요',
  loginValidationPasswordTooShort: '비밀번호는 8자 이상이어야 합니다',
  loginValidationPasswordMismatch: '비밀번호 확인이 일치하지 않습니다',
  loginValidationCodeRequired: '인증 코드를 입력해 주세요',
  savedEmptyTitle: '아직 저장된 카트가 없어요',
  savedEmptyBody: 'Home에서 저장하면 여기서 다시 볼 수 있어.',
  recentSavedTitle: '최근 저장 카트',
  recentSavedEmptyBody: '아직 저장된 카트가 없어요. 현재 카트를 저장하면 다음 쇼핑 전에 다시 꺼내볼 수 있어요.',
  myBenefitsTitle: '계정이 있으면 좋은 점',
  myBenefitsBody: '• 저장한 카트를 계속 보기\n• 최근 스캔 결과 이어보기\n• 다음 쇼핑 전에 다시 꺼내 비교하기',
  myGuestModeLabel: '게스트로 사용 중이에요',
  myLoginAction: '로그인 / 회원가입',
  myLogoutAction: '로그아웃',
  myLinkedDoneMessage: '계정을 연결했어요',
  myLogoutDoneMessage: '로그아웃했어요',
  drawerGuestTitle: '아직 로그인하지 않았어요',
  drawerGuestBody: '저장한 카트와 스캔 기록을 이어가려면 로그인해.',
  saveCompleteTitle: '카트 저장 완료',
  saveCompleteSubtitle: '다음 장보기 전에 다시 볼 수 있어',
  saveCompleteViewSavedAction: '지난 카트 보기',
  scanCaptureButton: '가격표 인식하기',
  scanUploadButton: '이미지 파일을 업로드 하세요',
  scanManualAddAction: '직접 추가하기',
  scanRecognizedTitle: '인식 결과',
  scanManualAddTitle: '직접 추가하기',
  scanUploading: '업로드 중...',
  scanQueued: '대기 중...',
  scanProcessing: '분석 중...',
  scanResultPreparing: '결과 정리 중...',
  scanFailed: '인식에 실패했어요',
  scanTimeout: '분석이 조금 지연되고 있어요. 잠시 후 다시 시도해봐요',
  scanResultEmpty: '텍스트를 못 읽었어요. 더 가까이/선명하게 찍어봐요',
  scanProcessingError: '분석 처리 중 오류가 났어요',
  scanRetakeAction: '다시 찍기',
  scanRecognizeAction: '인식',
  scanRecognizing: '인식 중...',
}

export const mockConfig = {
  remoteScan: true,
  adsEnabled: true,
  serviceName: 'Cartly API',
  storageRoot: '/Volumes/AI/WIMC',
  storageRootDisplay: '/Volumes/AI/Cartly',
  storageRootActual: '/Volumes/AI/WIMC',
  storageWritable: true,
  storagePaths: {
    root: '/Volumes/AI/Cartly',
    input: '/Volumes/AI/Cartly/input/2026-03-24',
    feedbackLogs: '/Volumes/AI/Cartly/logs/feedback/2026-03-24',
    failureLogs: '/Volumes/AI/Cartly/logs/failures/2026-03-24',
    failed: '/Volumes/AI/Cartly/failed/2026-03-24',
  },
  storageErrors: [],
  backendRunMode: 'terminal-login-session-supervised',
  runtimeAssetsRoot: '~/Library/Application Support/WIMC/assets',
  runtimeAssetsRootDisplay: '~/Library/Application Support/Cartly/assets',
  runtimeAssetsRootActual: '~/Library/Application Support/WIMC/assets',
  brandingAssetsDir: '~/Library/Application Support/WIMC/assets/branding',
  brandingAssetsDirDisplay: '~/Library/Application Support/Cartly/assets/branding',
  brandingAssetsDirActual: '~/Library/Application Support/WIMC/assets/branding',
  adsAssetsDir: '~/Library/Application Support/WIMC/assets/ads',
  adsAssetsDirDisplay: '~/Library/Application Support/Cartly/assets/ads',
  adsAssetsDirActual: '~/Library/Application Support/WIMC/assets/ads',
  legacyPathCompatibilityActive: true,
  apiBase: 'http://127.0.0.1:8011',
  branding: mockBranding,
}
